In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
plays = pd.read_csv("processed_data/remove_st_nbt_spikes/plays.csv",index_col=0)
plays.head()

,level_0,index,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
0,0,0,2018090600:75:1,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,I_FORM,"2 RB, 1 TE, 2 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False
1,1,1,2018090600:146:1,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,13:10:00,49.0,NaN,NaN,I,0,0,-0.372360,False
2,2,2,2018090600:168:1,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,SHOTGUN,"2 RB, 1 TE, 2 WR",6.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,13:05:00,49.0,NaN,NaN,I,0,0,-0.702779,False
3,3,3,2018090600:190:1,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,5.0,"4 DL, 1 LB, 6 DB",SCRAMBLE_ROLLOUT_LEFT,0.0,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False
4,4,4,2018090600:256:1,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,SHOTGUN,"2 RB, 3 TE, 0 WR",8.0,6.0,"6 DL, 3 LB, 2 DB",TRADITIONAL,0.0,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False

Es interesante poner primero estos valores porque para la visualización de los datos es imposible hacerlo sin este valor, por eso se trata antes que cualquier otra columna

In [4]:
plays[plays["absoluteYardlineNumber"].isnull()]

,level_0,index,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
22,22,22,2018090600:1226:1,(8:23) (Shotgun) N.Foles pass incomplete short...,2,3,7,PHI,play_type_unknown,ATL,17,NaN,"1 RB, 1 TE, 3 WR",NaN,NaN,"3 DL, 3 LB, 5 DB",NaN,NaN,NaN,NaN,NaN,DPI,ATL 21,I,0,8,1.169181,True
31,31,31,2018090600:1715:1,(1:50) (Shotgun) N.Foles pass short right to N...,2,1,10,PHI,play_type_unknown,PHI,24,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,NaN,"3 DL, 3 LB, 5 DB",NaN,NaN,NaN,NaN,NaN,DH,ATL 21,C,7,5,0.169598,False
43,43,43,2018090600:2305:1,(13:44) (Shotgun) N.Foles pass incomplete shor...,3,1,10,PHI,play_type_unknown,PHI,36,SHOTGUN,"1 RB, 2 TE, 2 WR",7.0,NaN,"3 DL, 3 LB, 5 DB",NaN,NaN,NaN,NaN,NaN,ICT,ATL 23,I,0,5,0.309866,False
67,67,67,2018090600:3626:1,(8:31) (Shotgun) N.Foles pass short right to N...,4,3,4,PHI,play_type_unknown,PHI,31,SHOTGUN,"1 RB, 2 TE, 2 WR",6.0,NaN,"3 DL, 3 LB, 5 DB",NaN,NaN,NaN,NaN,NaN,OPI,PHI 86,C,10,-10,-0.694743,False
87,87,87,2018090600:4439:1,(:06) (Shotgun) M.Ryan pass incomplete short r...,4,4,10,ATL,play_type_unknown,PHI,10,EMPTY,"1 RB, 1 TE, 3 WR",5.0,NaN,"4 DL, 1 LB, 6 DB",NaN,NaN,NaN,NaN,NaN,ICT,PHI 58,I,0,5,1.383655,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18981,19055,19102,2018123013:4238:17,(1:55) (Shotgun) G.Smith sacked at LAC 18 for ...,4,3,15,LAC,play_type_unknown,LAC,26,SHOTGUN,"1 RB, 1 TE, 3 WR",8.0,NaN,"3 DL, 4 LB, 4 DB",NaN,NaN,NaN,NaN,NaN,DH,DEN 41,S,-8,5,0.887859,False
18998,19072,19119,2018123014:1212:17,(15:00) (Shotgun) J.Goff pass short left to J....,2,2,15,LA,play_type_unknown,LA,44,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,NaN,"4 DL, 2 LB, 5 DB",NaN,NaN,NaN,NaN,NaN,ICT,SF 24,C,13,5,0.840261,False
19013,19087,19134,2018123014:2022:17,(4:08) (Shotgun) N.Mullens pass incomplete sho...,2,2,9,SF,play_type_unknown,LA,48,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,NaN,"4 DL, 3 LB, 4 DB",NaN,NaN,NaN,NaN,NaN,RPS,LA 26,I,0,15,1.218791,False
19016,19090,19137,2018123014:2170:17,(2:18) (Shotgun) N.Mullens pass incomplete sho...,2,3,6,SF,play_type_unknown,LA,14,EMPTY,"1 RB, 1 TE, 3 WR",4.0,NaN,"3 DL, 3 LB, 5 DB",NaN,NaN,NaN,NaN,NaN,DH,LA 58,I,0,5,0.848771,False
19097,19172,19219,2018123015:2742:17,(6:13) (Shotgun) R.Wilson sacked at SEA 3 for ...,3,3,6,SEA,play_type_unknown,SEA,6,EMPTY,"0 RB, 1 TE, 4 WR",5.0,NaN,"4 DL, 2 LB, 5 DB",NaN,NaN,NaN,NaN,NaN,DH,ARI 43,S,-3,5,1.795895,False

Para recuperar esa información, podemos hacerlo a través de la posición del balón (la x), que sabemos que está en todos primeros frames de cada jugada.
Por eso tenemos que cargar todas las semanas

In [5]:
week1 = pd.read_csv("processed_data/remove_st_nbt_spikes/week1.csv")
week2 = pd.read_csv("processed_data/remove_st_nbt_spikes/week2.csv")
week3 = pd.read_csv("processed_data/remove_st_nbt_spikes/week3.csv")
week4 = pd.read_csv("processed_data/remove_st_nbt_spikes/week4.csv")
week5 = pd.read_csv("processed_data/remove_st_nbt_spikes/week5.csv")
week6 = pd.read_csv("processed_data/remove_st_nbt_spikes/week6.csv")
week7 = pd.read_csv("processed_data/remove_st_nbt_spikes/week7.csv")
week8 = pd.read_csv("processed_data/remove_st_nbt_spikes/week8.csv")
week9 = pd.read_csv("processed_data/remove_st_nbt_spikes/week9.csv")
week10 = pd.read_csv("processed_data/remove_st_nbt_spikes/week10.csv")
week11 = pd.read_csv("processed_data/remove_st_nbt_spikes/week11.csv")
week12 = pd.read_csv("processed_data/remove_st_nbt_spikes/week12.csv")
week13 = pd.read_csv("processed_data/remove_st_nbt_spikes/week13.csv")
week14 = pd.read_csv("processed_data/remove_st_nbt_spikes/week14.csv")
week15 = pd.read_csv("processed_data/remove_st_nbt_spikes/week15.csv")
week16 = pd.read_csv("processed_data/remove_st_nbt_spikes/week16.csv")
week17 = pd.read_csv("processed_data/remove_st_nbt_spikes/week17.csv")
week1.head()

,Unnamed: 0,level_0,Unnamed: 0.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,0,0,0,0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,1,1,1,1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2,2,2,2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,3,3,3,3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,4,4,4,4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH

In [6]:
weeks = [week1,week2,week3,week4,week5,week6,week7,week8,week9,week10,week11,week12,week13,week14,week15,week16,week17]

In [7]:
for index,row in plays[plays["absoluteYardlineNumber"].isnull()].iterrows():
    week = row["id"].split(":")
    plays.loc[plays['id']==row["id"], ["absoluteYardlineNumber"]] = round(weeks[int(week[2])-1][(weeks[int(week[2])-1]["id"]==row["id"]) & (weeks[int(week[2])-1]["displayName"]=="Football")]["x"].values[0])

In [8]:
plays.isnull().sum()

level_0                       0
index                         0
id                            0
playDescription               0
quarter                       0
down                          0
yardsToGo                     0
possessionTeam                0
playType                      0
yardlineSide                252
yardlineNumber                0
offenseFormation             50
personnelO                   29
defendersInTheBox            46
numberOfPassRushers         633
personnelD                   29
typeDropback                639
preSnapVisitorScore         639
preSnapHomeScore            639
gameClock                   639
absoluteYardlineNumber        0
penaltyCodes              17913
penaltyJerseyNumbers      17913
passResult                    2
offensePlayResult             0
playResult                    0
epa                           0
isDefensivePI                 0
dtype: int64

In [9]:
plays.to_csv("processed_data/remove_st_nbt_spikes/plays.csv")