In [1]:
import pandas as pd
import pickle

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
week1 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week1.csv")
week2 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week2.csv")
week3 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week3.csv")
week4 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week4.csv")
week5 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week5.csv")
week6 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week6.csv")
week7 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week7.csv")
week8 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week8.csv")
week9 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week9.csv")
week10 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week10.csv")
week11 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week11.csv")
week12 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week12.csv")
week13 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week13.csv")
week14 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week14.csv")
week15 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week15.csv")
week16 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week16.csv")
week17 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week17.csv")
week1.head()

,Unnamed: 0,Unnamed: 0.1,level_0,Unnamed: 0.1.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,0,0,0,0,0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,1,1,1,1,1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2,2,2,2,2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,3,3,3,3,3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,4,4,4,4,4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH

In [4]:
week1_f1 = week1[week1["frameId"]==1]
week2_f1 = week2[week2["frameId"]==1]
week3_f1 = week3[week3["frameId"]==1]
week4_f1 = week4[week4["frameId"]==1]
week5_f1 = week5[week5["frameId"]==1]
week6_f1 = week6[week6["frameId"]==1]
week7_f1 = week7[week7["frameId"]==1]
week8_f1 = week8[week8["frameId"]==1]
week9_f1 = week9[week9["frameId"]==1]
week10_f1 = week10[week10["frameId"]==1]
week11_f1 = week11[week11["frameId"]==1]
week12_f1 = week12[week12["frameId"]==1]
week13_f1 = week13[week13["frameId"]==1]
week14_f1 = week14[week14["frameId"]==1]
week15_f1 = week15[week15["frameId"]==1]
week16_f1 = week16[week16["frameId"]==1]
week17_f1 = week17[week17["frameId"]==1]
week1_f1

,Unnamed: 0,Unnamed: 0.1,level_0,Unnamed: 0.1.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,0,0,0,0,0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,1,1,1,1,1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2,2,2,2,2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,3,3,3,3,3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,4,4,4,4,4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982403,984550,984550,985057,985057,985057,2018091001:4192:1,2018-09-11T05:29:33.500Z,35.90,24.39,0.00,0.00,0.00,97.08,258.63,None,2556277.0,Marqui Christian,41.0,SS,1,away,left,NaN
982404,984551,984551,985058,985058,985058,2018091001:4192:1,2018-09-11T05:29:33.500Z,36.93,36.39,0.02,0.02,0.01,95.57,111.48,None,2556593.0,Cory Littleton,58.0,ILB,1,away,left,NaN
982405,984552,984552,985059,985059,985059,2018091001:4192:1,2018-09-11T05:29:33.500Z,42.53,46.29,0.00,0.00,0.00,266.37,339.77,None,2556885.0,Jalen Richard,30.0,RB,1,home,left,SCREEN
982406,984553,984553,985060,985060,985060,2018091001:4192:1,2018-09-11T05:29:33.500Z,29.08,35.13,0.02,0.02,0.01,104.77,290.71,None,2558183.0,John Johnson,43.0,SS,1,away,left,NaN
982407,984554,984554,985061,985061,985061,2018091001:4192:1,2018-09-11T05:29:33.500Z,41.00,29.62,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,left,NaN

In [5]:
weeks_f1 = [week1_f1,week2_f1,week3_f1,week4_f1,week5_f1,week6_f1,week7_f1,week8_f1,week9_f1,week10_f1,week11_f1,week12_f1,week13_f1,week14_f1,week15_f1,week16_f1,week17_f1]

In [6]:
week1_f1.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'level_0', 'Unnamed: 0.1.1', 'index',
       'id', 'time', 'x', 'y', 's', 'a', 'dis', 'o', 'dir', 'event', 'nflId',
       'displayName', 'jerseyNumber', 'position', 'frameId', 'team',
       'playDirection', 'route'],
      dtype='object')

In [7]:
for week in weeks_f1:
    week.drop(['Unnamed: 0','Unnamed: 0.1','level_0','Unnamed: 0.1.1','index','time','frameId','route','event'],axis=1,inplace=True)

/home/villamor_coto/.local/lib/python3.9/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [8]:
week3_f1

,id,x,y,s,a,dis,o,dir,nflId,displayName,jerseyNumber,position,team,playDirection
0,2018092000:51:3,33.47,26.91,0.00,0.01,0.01,82.28,245.04,2495240.0,Tyrod Taylor,5.0,QB,home,right
1,2018092000:51:3,36.32,11.84,0.46,0.80,0.05,278.40,312.33,2532877.0,Trumaine Johnson,22.0,CB,away,right
2,2018092000:51:3,35.79,17.36,0.41,0.37,0.04,287.41,338.27,2533059.0,Morris Claiborne,21.0,CB,away,right
3,2018092000:51:3,33.62,31.43,0.02,0.03,0.02,104.03,250.29,2540928.0,Darren Fells,88.0,TE,home,right
4,2018092000:51:3,33.38,17.42,0.01,0.01,0.00,81.26,80.56,2543488.0,Jarvis Landry,80.0,WR,home,right
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1162639,2018092400:4286:3,34.16,26.49,0.00,0.00,0.01,84.58,101.56,2557978.0,James Conner,30.0,RB,away,right
1162640,2018092400:4286:3,40.51,34.88,0.00,0.00,0.00,5.54,311.71,2558149.0,JuJu Smith-Schuster,19.0,WR,away,right
1162641,2018092400:4286:3,44.36,20.42,0.03,0.02,0.01,291.05,64.54,2560930.0,Jordan Whitehead,31.0,DB,home,right
1162642,2018092400:4286:3,43.03,36.99,0.08,0.08,0.01,254.79,248.89,2561039.0,Carlton Davis,33.0,CB,home,right
1162643,2018092400:4286:3,42.10,26.75,0.00,0.00,0.00,NaN,NaN,NaN,Football,NaN,NaN,football,right

In [9]:
all_players = pd.concat(weeks_f1)

In [11]:
all_players.to_csv("processed_data/weeks_frame1/frame1_process/all_players_play.csv")