In [1]:
import pandas as pd
import pickle
import os

In [2]:
week1 = pd.read_csv("processed_data/weeks/week1_ordered.csv",index_col=0)
week2 = pd.read_csv("processed_data/weeks/week2_ordered.csv",index_col=0)
week3 = pd.read_csv("processed_data/weeks/week3_ordered.csv",index_col=0)
week4 = pd.read_csv("processed_data/weeks/week4_ordered.csv",index_col=0)
week5 = pd.read_csv("processed_data/weeks/week5_ordered.csv",index_col=0)
week6 = pd.read_csv("processed_data/weeks/week6_ordered.csv",index_col=0)
week7 = pd.read_csv("processed_data/weeks/week7_ordered.csv",index_col=0)
week8 = pd.read_csv("processed_data/weeks/week8_ordered.csv",index_col=0)
week9 = pd.read_csv("processed_data/weeks/week9_ordered.csv",index_col=0)
week10 = pd.read_csv("processed_data/weeks/week10_ordered.csv",index_col=0)
week11 = pd.read_csv("processed_data/weeks/week11_ordered.csv",index_col=0)
week12 = pd.read_csv("processed_data/weeks/week12_ordered.csv",index_col=0)
week13 = pd.read_csv("processed_data/weeks/week13_ordered.csv",index_col=0)
week14 = pd.read_csv("processed_data/weeks/week14_ordered.csv",index_col=0)
week15 = pd.read_csv("processed_data/weeks/week15_ordered.csv",index_col=0)
week16 = pd.read_csv("processed_data/weeks/week16_ordered.csv",index_col=0)
week17 = pd.read_csv("processed_data/weeks/week17_ordered.csv",index_col=0)
week1.head()

/home/villamor_coto/.local/lib/python3.9/site-packages/numpy/lib/arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH

In [3]:
week1.isnull().sum()

id                    0
time                  0
x                     0
y                     0
s                     0
a                     0
dis                   0
o                 66913
dir               66913
event                 0
nflId             66913
displayName           0
jerseyNumber      66913
position          66913
frameId               0
team                  0
playDirection         0
route            712708
dtype: int64

In [4]:
week1[week1["displayName"]=="Football"]

,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
13,2018090600:75:1,2018-09-07T01:07:14.599Z,90.11,26.85,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,left,NaN
27,2018090600:75:1,2018-09-07T01:07:14.700Z,90.11,26.85,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,2,football,left,NaN
41,2018090600:75:1,2018-09-07T01:07:14.799Z,90.11,26.85,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,3,football,left,NaN
55,2018090600:75:1,2018-09-07T01:07:14.900Z,90.11,26.85,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,4,football,left,NaN
69,2018090600:75:1,2018-09-07T01:07:15.000Z,90.11,26.85,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,5,football,left,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985961,2018091001:4192:1,2018-09-11T05:29:39.500Z,34.09,43.18,3.89,3.32,0.40,NaN,NaN,None,NaN,Football,NaN,NaN,61,football,left,NaN
985976,2018091001:4192:1,2018-09-11T05:29:39.599Z,33.84,43.42,3.31,3.72,0.35,NaN,NaN,None,NaN,Football,NaN,NaN,62,football,left,NaN
985991,2018091001:4192:1,2018-09-11T05:29:39.700Z,33.62,43.63,2.84,3.99,0.30,NaN,NaN,None,NaN,Football,NaN,NaN,63,football,left,NaN
986006,2018091001:4192:1,2018-09-11T05:29:39.799Z,33.44,43.80,2.29,4.20,0.25,NaN,NaN,tackle,NaN,Football,NaN,NaN,64,football,left,NaN
986021,2018091001:4192:1,2018-09-11T05:29:39.900Z,33.29,43.92,1.81,4.24,0.20,NaN,NaN,None,NaN,Football,NaN,NaN,65,football,left,NaN

In [5]:
weeks = [week1,week2,week3,week4,week5,week6,week7,week8,week9,week10,week11,week12,week13,week14,week15,week16,week17]

In [6]:
for week in weeks:
    if week["nflId"].isnull().sum() != len(week[week["displayName"]=="Football"]):
        print("error")

There is no empty values.

In [7]:
special_team_positions = ['P','LS','K']

In [8]:
special_team_play = []

In [9]:
week1_f1 = week1[week1["frameId"]==1]
week2_f1 = week2[week2["frameId"]==1]
week3_f1 = week3[week3["frameId"]==1]
week4_f1 = week4[week4["frameId"]==1]
week5_f1 = week5[week5["frameId"]==1]
week6_f1 = week6[week6["frameId"]==1]
week7_f1 = week7[week7["frameId"]==1]
week8_f1 = week8[week8["frameId"]==1]
week9_f1 = week9[week9["frameId"]==1]
week10_f1 = week10[week10["frameId"]==1]
week11_f1 = week11[week11["frameId"]==1]
week12_f1 = week12[week12["frameId"]==1]
week13_f1 = week13[week13["frameId"]==1]
week14_f1 = week14[week14["frameId"]==1]
week15_f1 = week15[week15["frameId"]==1]
week16_f1 = week16[week16["frameId"]==1]
week17_f1 = week17[week17["frameId"]==1]

In [10]:
weeks_f1 = [week1_f1,week2_f1,week3_f1,week4_f1,week5_f1,week6_f1,week7_f1,week8_f1,week9_f1,week10_f1,week11_f1,week12_f1,week13_f1,week14_f1,week15_f1,week16_f1,week17_f1]

In [11]:
count = 1
for week in weeks_f1:
    print(count)
    for index,row in week.iterrows():
        if row["position"] in special_team_positions and row["id"] not in special_team_play:
            special_team_play.append(row["id"])
    count+=1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17

In [12]:
special_team_play

['2018091607:329:2',
 '2018092309:2100:3',
 '2018092700:2608:4',
 '2018093011:544:4',
 '2018100700:1558:5',
 '2018102810:1243:8',
 '2018110402:1544:9',
 '2018111104:2472:10',
 '2018111106:554:10',
 '2018111808:1165:11',
 '2018112509:2125:12',
 '2018120200:1137:13',
 '2018120901:1570:14',
 '2018121611:3142:15',
 '2018123002:1229:17',
 '2018123012:2739:17']

In [14]:
pickle_file = open('special_team_plays.pickle','wb')
pickle.dump(special_team_play,pickle_file)
pickle_file.close()

In [18]:
offense_positions = ['QB','WR','RB','TE','FB','HB']
defense_positions = ['SS','FS','MLB','CB','LB','OLB','ILB','DL','DB','NT','S','DT']

In [20]:
not_both_teams = []
for week in weeks_f1:
    values = week["id"].unique()
    for play in values:
        positions = week[week["id"]==play]["position"].unique()
        offense = False
        defense = False
        for player in positions:
            if player in offense_positions:
                offense = True
            if player in defense_positions:
                defense = True
        
        if offense != True or defense != True:
            if offense != True:
                print("No offense in play: ",play)
                not_both_teams.append(play)
            if defense != True:
                print("No defense in play: ",play)
                not_both_teams.append(play)

No defense in play:  2018092000:1539:3
No defense in play:  2018092305:1553:3
No defense in play:  2018092400:1867:3
No offense in play:  2018093005:168:4
No defense in play:  2018101412:1559:6
No offense in play:  2018101412:1922:6
No offense in play:  2018101412:1946:6
No offense in play:  2018102101:2734:7
No offense in play:  2018102500:1655:8
No offense in play:  2018102809:298:8
No offense in play:  2018102809:3344:8
No offense in play:  2018102810:436:8
No offense in play:  2018102811:1119:8
No offense in play:  2018110402:2502:9
No defense in play:  2018110405:1062:9
No offense in play:  2018110406:1226:9
No offense in play:  2018111803:178:11
No offense in play:  2018112500:765:12
No defense in play:  2018112500:1824:12
No offense in play:  2018112504:3114:12
No offense in play:  2018112510:937:12
No offense in play:  2018120204:3828:13
No offense in play:  2018120600:1343:14
No defense in play:  2018120911:4000:14
No offense in play:  2018121500:1129:15
No offense in play:  2018121500:3860:15
No offense in play:  2018121700:1865:15
No offense in play:  2018121700:2267:15
No defense in play:  2018122307:4434:16
No offense in play:  2018123004:2309:17
No offense in play:  2018123010:334:17

In [21]:
not_both_teams

['2018092000:1539:3',
 '2018092305:1553:3',
 '2018092400:1867:3',
 '2018093005:168:4',
 '2018101412:1559:6',
 '2018101412:1922:6',
 '2018101412:1946:6',
 '2018102101:2734:7',
 '2018102500:1655:8',
 '2018102809:298:8',
 '2018102809:3344:8',
 '2018102810:436:8',
 '2018102811:1119:8',
 '2018110402:2502:9',
 '2018110405:1062:9',
 '2018110406:1226:9',
 '2018111803:178:11',
 '2018112500:765:12',
 '2018112500:1824:12',
 '2018112504:3114:12',
 '2018112510:937:12',
 '2018120204:3828:13',
 '2018120600:1343:14',
 '2018120911:4000:14',
 '2018121500:1129:15',
 '2018121500:3860:15',
 '2018121700:1865:15',
 '2018121700:2267:15',
 '2018122307:4434:16',
 '2018123004:2309:17',
 '2018123010:334:17']

In [35]:
for play in not_both_teams:
    id_parts = play.split(":")
    week = id_parts[2]
    if len(weeks[int(week)-1][weeks[int(week)-1]["id"]== play]["team"].unique()) != 2:
        print("Error")

In [36]:
pickle_file = open('resources/not_both_teams.pickle','wb')
pickle.dump(not_both_teams,pickle_file)
pickle_file.close()