In [1]:
import pandas as pd
import pickle

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
plays = pd.read_csv("processed_data/remove_st_nbt_spikes/plays.csv",index_col=0)
plays.head()

,level_0,index,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
0,0,0,2018090600:75:1,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,I_FORM,"2 RB, 1 TE, 2 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False
1,1,1,2018090600:146:1,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,13:10:00,49.0,NaN,NaN,I,0,0,-0.372360,False
2,2,2,2018090600:168:1,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,SHOTGUN,"2 RB, 1 TE, 2 WR",6.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,13:05:00,49.0,NaN,NaN,I,0,0,-0.702779,False
3,3,3,2018090600:190:1,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,5.0,"4 DL, 1 LB, 6 DB",SCRAMBLE_ROLLOUT_LEFT,0.0,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False
4,4,4,2018090600:256:1,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,SHOTGUN,"2 RB, 3 TE, 0 WR",8.0,6.0,"6 DL, 3 LB, 2 DB",TRADITIONAL,0.0,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False

In [4]:
week1 = pd.read_csv("processed_data/remove_st_nbt_spikes/week1.csv")
week2 = pd.read_csv("processed_data/remove_st_nbt_spikes/week2.csv")
week3 = pd.read_csv("processed_data/remove_st_nbt_spikes/week3.csv")
week4 = pd.read_csv("processed_data/remove_st_nbt_spikes/week4.csv")
week5 = pd.read_csv("processed_data/remove_st_nbt_spikes/week5.csv")
week6 = pd.read_csv("processed_data/remove_st_nbt_spikes/week6.csv")
week7 = pd.read_csv("processed_data/remove_st_nbt_spikes/week7.csv")
week8 = pd.read_csv("processed_data/remove_st_nbt_spikes/week8.csv")
week9 = pd.read_csv("processed_data/remove_st_nbt_spikes/week9.csv")
week10 = pd.read_csv("processed_data/remove_st_nbt_spikes/week10.csv")
week11 = pd.read_csv("processed_data/remove_st_nbt_spikes/week11.csv")
week12 = pd.read_csv("processed_data/remove_st_nbt_spikes/week12.csv")
week13 = pd.read_csv("processed_data/remove_st_nbt_spikes/week13.csv")
week14 = pd.read_csv("processed_data/remove_st_nbt_spikes/week14.csv")
week15 = pd.read_csv("processed_data/remove_st_nbt_spikes/week15.csv")
week16 = pd.read_csv("processed_data/remove_st_nbt_spikes/week16.csv")
week17 = pd.read_csv("processed_data/remove_st_nbt_spikes/week17.csv")
week1.head()

,Unnamed: 0,level_0,Unnamed: 0.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,0,0,0,0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,1,1,1,1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2,2,2,2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,3,3,3,3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,4,4,4,4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH

In [5]:
week1_f1 = week1[week1["frameId"]==1]
week2_f1 = week2[week2["frameId"]==1]
week3_f1 = week3[week3["frameId"]==1]
week4_f1 = week4[week4["frameId"]==1]
week5_f1 = week5[week5["frameId"]==1]
week6_f1 = week6[week6["frameId"]==1]
week7_f1 = week7[week7["frameId"]==1]
week8_f1 = week8[week8["frameId"]==1]
week9_f1 = week9[week9["frameId"]==1]
week10_f1 = week10[week10["frameId"]==1]
week11_f1 = week11[week11["frameId"]==1]
week12_f1 = week12[week12["frameId"]==1]
week13_f1 = week13[week13["frameId"]==1]
week14_f1 = week14[week14["frameId"]==1]
week15_f1 = week15[week15["frameId"]==1]
week16_f1 = week16[week16["frameId"]==1]
week17_f1 = week17[week17["frameId"]==1]
week1_f1

,Unnamed: 0,level_0,Unnamed: 0.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,0,0,0,0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,1,1,1,1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2,2,2,2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,3,3,3,3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,4,4,4,4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984550,984550,985057,985057,985057,2018091001:4192:1,2018-09-11T05:29:33.500Z,35.90,24.39,0.00,0.00,0.00,97.08,258.63,None,2556277.0,Marqui Christian,41.0,SS,1,away,left,NaN
984551,984551,985058,985058,985058,2018091001:4192:1,2018-09-11T05:29:33.500Z,36.93,36.39,0.02,0.02,0.01,95.57,111.48,None,2556593.0,Cory Littleton,58.0,ILB,1,away,left,NaN
984552,984552,985059,985059,985059,2018091001:4192:1,2018-09-11T05:29:33.500Z,42.53,46.29,0.00,0.00,0.00,266.37,339.77,None,2556885.0,Jalen Richard,30.0,RB,1,home,left,SCREEN
984553,984553,985060,985060,985060,2018091001:4192:1,2018-09-11T05:29:33.500Z,29.08,35.13,0.02,0.02,0.01,104.77,290.71,None,2558183.0,John Johnson,43.0,SS,1,away,left,NaN
984554,984554,985061,985061,985061,2018091001:4192:1,2018-09-11T05:29:33.500Z,41.00,29.62,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,left,NaN

In [6]:
weeks_f1 = [week1_f1,week2_f1,week3_f1,week4_f1,week5_f1,week6_f1,week7_f1,week8_f1,week9_f1,week10_f1,week11_f1,week12_f1,week13_f1,week14_f1,week15_f1,week16_f1,week17_f1]

Calculamos la posición del balón respecto a la línea de Scrimmage

In [7]:
plays_line_far = []
for index,row in plays.iterrows():
    id_parts = row["id"].split(":")
    week = id_parts[2]
    absoluteYardLine = round(weeks_f1[int(week)-1][(weeks_f1[int(week)-1]["id"]==row["id"])&(weeks_f1[int(week)-1]["displayName"]=="Football")]["x"].values[0])
    if abs(absoluteYardLine - int(row["absoluteYardlineNumber"])) > 2:
        plays_line_far.append(row["id"])

In [8]:
plays_line_far

['2018093006:623:4',
 '2018093006:656:4',
 '2018100710:3616:5',
 '2018101404:2003:6',
 '2018101410:431:6',
 '2018101412:2923:6',
 '2018101800:1846:7',
 '2018102101:1894:7',
 '2018102101:2687:7',
 '2018102101:3078:7',
 '2018102102:3411:7',
 '2018102108:2950:7',
 '2018102200:2263:7',
 '2018102804:2133:8',
 '2018102808:2190:8',
 '2018102809:1123:8',
 '2018110100:1565:9',
 '2018110401:3027:9',
 '2018110410:2666:9',
 '2018110410:2843:9',
 '2018110410:3640:9',
 '2018110500:822:9',
 '2018110500:1501:9',
 '2018110500:2799:9',
 '2018111104:3933:10',
 '2018111108:251:10',
 '2018112504:181:12',
 '2018112505:2232:12',
 '2018112510:3572:12',
 '2018120207:3714:13',
 '2018120207:4701:13',
 '2018120209:3288:13',
 '2018120212:162:13',
 '2018120212:1180:13',
 '2018120900:2705:14',
 '2018120900:2855:14',
 '2018120901:2858:14',
 '2018120906:858:14',
 '2018120906:1287:14',
 '2018120906:1312:14',
 '2018120906:2152:14',
 '2018120912:3780:14',
 '2018120913:2723:14',
 '2018120913:2828:14',
 '2018120913:3106:14',
 '2018120913:3204:14',
 '2018120913:3938:14',
 '2018120913:4138:14',
 '2018121300:753:15',
 '2018121609:217:15',
 '2018121700:206:15',
 '2018121700:2048:15',
 '2018122400:2211:16',
 '2018123001:435:17',
 '2018123006:476:17',
 '2018123006:788:17',
 '2018123006:3113:17',
 '2018123008:171:17']

In [9]:
pickle_file = open('resources/plays_line_far.pickle','wb')
pickle.dump(plays_line_far,pickle_file)
pickle_file.close()

Algunas jugadas no tienen el valor o aparece fuera del campo cuando es el primer frame. Habrá que ver la posición del balón.

Ahora miramos que ningún jugador sobre pase la línea de scrimmage

In [10]:
players_over_line = []
for week in weeks_f1:
    for index,row in week.iterrows():
        playDirection = row["playDirection"]
        if row["position"] in ['QB','WR','RB','TE','FB','HB']:
            if playDirection == "right":
                if row["x"] > plays[plays["id"]==row["id"]]["absoluteYardlineNumber"].values[0]:
                    players_over_line.append(row["id"])
            if playDirection == "left":
                if row["x"] < plays[plays["id"]==row["id"]]["absoluteYardlineNumber"].values[0]:
                    players_over_line.append(row["id"])

In [11]:
pickle_file = open('resources/players_over_line.pickle','wb')
pickle.dump(players_over_line,pickle_file)
pickle_file.close()

Vamos a ver ciertas jugadas donde el balón esté muy distanciado del jugador que esté en "perpendicular" (damos un margen de 3 yardas tanto a la derecha como a la izquierda)

In [7]:
football_is_far = []
football_is_outside = []
for week in weeks_f1:
    playsids = week["id"].unique()
    for play in playsids:
        yFootball = int(week[(week["displayName"]=="Football")&(week["id"]==play)]["y"].values[0])
        offensePlayers = week[(week["id"]==play)&(week["position"].isin(['QB','WR','RB','TE','FB','HB']))]
        align = False
        for index,row in offensePlayers.iterrows():
            yPlayer = int(row["y"])
            if abs(yPlayer - yFootball) < 3:
                align = True
                
        if not(align):
            if yFootball > 53.3 or yFootball < 0:
                football_is_outside.append(play)
            else:
                football_is_far.append(play)

In [8]:
football_is_far

['2018100702:4007:5',
 '2018101403:1284:6',
 '2018102101:3078:7',
 '2018120906:1025:14',
 '2018120906:1312:14',
 '2018120906:1416:14',
 '2018121000:1364:14']

In [14]:
pickle_file = open('resources/football_is_far.pickle','wb')
pickle.dump(football_is_far,pickle_file)
pickle_file.close()

In [9]:
pickle_file = open('resources/football_is_outside.pickle','wb')
pickle.dump(football_is_outside,pickle_file)
pickle_file.close()

Muchas de las jugadas tienen el valor fuera y una correcta posición de los jugadores (eso es interesante para el estudio) aunque una jugada le faltaba un QB y aparece en la descripción. Habrá que verla detenidamente