In [1]:
import pandas as pd
import pickle

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
pickle_file_no_one_qb = open('resources/no_one_qb.pickle','rb')
pickle_file_repeated_players = open('resources/two_qbs_same.pickle','rb')
pickle_file_not_same_personnelO = open('resources/not_same_personnelO.pickle','rb')
pickle_file_not_same_personnelD = open('resources/not_same_personnelD.pickle','rb')
pickle_file_defense_strange_density = open('resources/defense_strange_density.pickle','rb')
no_one_qb = pickle.load(pickle_file_no_one_qb)
repeated_players = pickle.load(pickle_file_repeated_players)
not_same_personnelO = pickle.load(pickle_file_not_same_personnelO)
not_same_personnelD = pickle.load(pickle_file_not_same_personnelD)
defense_strange_density = pickle.load(pickle_file_defense_strange_density)
pickle_file_no_one_qb.close()
pickle_file_repeated_players.close()
pickle_file_not_same_personnelO.close()
pickle_file_not_same_personnelD.close()
pickle_file_defense_strange_density.close()

In [4]:
plays = pd.read_csv("processed_data/remove_st_nbt_spikes/plays.csv",index_col=0)
plays.head()

,level_0,index,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
0,0,0,2018090600:75:1,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,I_FORM,"2 RB, 1 TE, 2 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False
1,1,1,2018090600:146:1,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,13:10:00,49.0,NaN,NaN,I,0,0,-0.372360,False
2,2,2,2018090600:168:1,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,SHOTGUN,"2 RB, 1 TE, 2 WR",6.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,13:05:00,49.0,NaN,NaN,I,0,0,-0.702779,False
3,3,3,2018090600:190:1,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,5.0,"4 DL, 1 LB, 6 DB",SCRAMBLE_ROLLOUT_LEFT,0.0,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False
4,4,4,2018090600:256:1,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,SHOTGUN,"2 RB, 3 TE, 0 WR",8.0,6.0,"6 DL, 3 LB, 2 DB",TRADITIONAL,0.0,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False

In [5]:
week1 = pd.read_csv("processed_data/remove_st_nbt_spikes/week1.csv")
week2 = pd.read_csv("processed_data/remove_st_nbt_spikes/week2.csv")
week3 = pd.read_csv("processed_data/remove_st_nbt_spikes/week3.csv")
week4 = pd.read_csv("processed_data/remove_st_nbt_spikes/week4.csv")
week5 = pd.read_csv("processed_data/remove_st_nbt_spikes/week5.csv")
week6 = pd.read_csv("processed_data/remove_st_nbt_spikes/week6.csv")
week7 = pd.read_csv("processed_data/remove_st_nbt_spikes/week7.csv")
week8 = pd.read_csv("processed_data/remove_st_nbt_spikes/week8.csv")
week9 = pd.read_csv("processed_data/remove_st_nbt_spikes/week9.csv")
week10 = pd.read_csv("processed_data/remove_st_nbt_spikes/week10.csv")
week11 = pd.read_csv("processed_data/remove_st_nbt_spikes/week11.csv")
week12 = pd.read_csv("processed_data/remove_st_nbt_spikes/week12.csv")
week13 = pd.read_csv("processed_data/remove_st_nbt_spikes/week13.csv")
week14 = pd.read_csv("processed_data/remove_st_nbt_spikes/week14.csv")
week15 = pd.read_csv("processed_data/remove_st_nbt_spikes/week15.csv")
week16 = pd.read_csv("processed_data/remove_st_nbt_spikes/week16.csv")
week17 = pd.read_csv("processed_data/remove_st_nbt_spikes/week17.csv")
week1.head()

,Unnamed: 0,level_0,Unnamed: 0.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,0,0,0,0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,1,1,1,1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2,2,2,2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,3,3,3,3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,4,4,4,4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH

In [6]:
weeks = [week1,week2,week3,week4,week5,week6,week7,week8,week9,week10,week11,week12,week13,week14,week15,week16,week17]

In [7]:
remove_list = []
remove_list += no_one_qb
remove_list += repeated_players
remove_list += not_same_personnelO
remove_list += not_same_personnelD
remove_list += defense_strange_density

In [8]:
len(remove_list)

55

In [9]:
remove_list = list(set(remove_list))

In [10]:
len(remove_list)

54

In [11]:
for play in remove_list:
    id_parts = play.split(":")
    week = id_parts[2]
    plays.drop(plays[plays["id"]==play].index,inplace=True)
    weeks[int(week)-1].drop(weeks[int(week)-1][weeks[int(week)-1]["id"]== play].index,inplace=True)

In [12]:
week_number = 1
for week in weeks:
    week.to_csv("processed_data/remove_st_nbt_spikes_strangeplays/week{}.csv".format(week_number))
    week_number+=1

In [13]:
plays.to_csv("processed_data/remove_st_nbt_spikes_strangeplays/plays.csv")