In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import io

In [9]:
pd.set_option('display.max_columns',None)

In [2]:
all_plays = pd.read_csv("../processed_data/weeks_frame1/frame1_process/all_players_play.csv",index_col=0)
all_plays.head()

,id,x,y,s,a,dis,o,dir,nflId,displayName,jerseyNumber,position,team,playDirection
0,2018090600:75:1,91.73,26.67,0.00,0.01,0.02,289.57,240.93,310.0,Matt Ryan,2.0,QB,away,left
1,2018090600:75:1,88.89,36.47,0.01,0.01,0.01,105.63,66.66,79848.0,Malcolm Jenkins,27.0,SS,home,left
2,2018090600:75:1,91.35,44.16,0.02,0.03,0.01,290.45,16.86,2495454.0,Julio Jones,11.0,WR,away,left
3,2018090600:75:1,86.31,22.01,0.09,0.42,0.01,70.12,168.91,2495613.0,Corey Graham,24.0,FS,home,left
4,2018090600:75:1,90.78,36.15,0.00,0.00,0.00,257.61,193.97,2533040.0,Mohamed Sanu,12.0,WR,away,left

In [12]:
week6 = pd.read_csv("../processed_data/remove_st_nbt_spikes/week6.csv")

In [7]:
plays = pd.read_csv("../processed_data/processing_defenses/plays.csv",index_col=0)
plays.head()

,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,...,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI,redZone
0,2018090600:75:1,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,I_FORM,...,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False,False
1,2018090600:146:1,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,SINGLEBACK,...,13:10:00,49.0,NaN,NaN,I,0,0,-0.372360,False,False
2,2018090600:168:1,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,SHOTGUN,...,13:05:00,49.0,NaN,NaN,I,0,0,-0.702779,False,False
3,2018090600:190:1,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,SHOTGUN,...,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False,False
4,2018090600:256:1,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,SHOTGUN,...,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False,True

In [5]:
for play in all_plays["id"].unique():
    yFootball = all_plays[(all_plays["id"]==play)&(all_plays["displayName"]=="Football")]["y"].values[0]
    
    qb = all_plays[(all_plays["id"]==play)&(all_plays["position"] == "QB")]
    
    if len(qb) == 1 and abs(yFootball - qb["y"].values[0]) > 3:
        print(play)

2018091607:663:2
2018093006:2573:4
2018101403:1284:6
2018120906:1025:14
2018120906:1312:14

In [14]:
for play in all_plays["id"].unique():
    yFootball = all_plays[(all_plays["id"]==play)&(all_plays["displayName"]=="Football")]["y"].values[0]
    
    if yFootball > 53.3 or yFootball < 0:
        print(play)

2018101403:1284:6

In [16]:
for play in all_plays["id"].unique():
    yFootball = all_plays[(all_plays["id"]==play)&(all_plays["displayName"]=="Football")]["y"].values[0]
    
    if yFootball < 23.6 and yFootball > 29.7:
        print(play)

In [11]:
for index,row in plays.iterrows():
    if "Direct snap to" in row["playDescription"]:
        print(row["id"])

2018091607:663:2
2018093006:2573:4
2018102500:2829:8

In [13]:
week6[(week6["id"]=="2018101403:1284:6")&(week6["frameId"]==1)]

,Unnamed: 0,level_0,Unnamed: 0.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
339273,339273,339453,339453,339453,2018101403:1284:6,2018-10-14T17:48:56.099Z,28.45,12.02,0.07,0.05,0.00,24.53,284.38,None,2507817.0,Rafael Bush,20.0,SS,1,away,left,NaN
339274,339274,339454,339454,339454,2018101403:1284:6,2018-10-14T17:48:56.099Z,38.98,23.78,0.02,0.02,0.01,282.56,317.90,None,2533034.0,Lamar Miller,26.0,RB,1,home,left,WHEEL
339275,339275,339455,339455,339455,2018101403:1284:6,2018-10-14T17:48:56.099Z,18.04,17.03,1.01,0.24,0.10,62.45,130.87,None,2539240.0,Micah Hyde,23.0,SS,1,away,left,NaN
339276,339276,339456,339456,339456,2018101403:1284:6,2018-10-14T17:48:56.099Z,23.20,28.28,1.01,0.51,0.10,111.78,100.58,None,2539290.0,Jordan Poyer,21.0,FS,1,away,left,NaN
339277,339277,339457,339457,339457,2018101403:1284:6,2018-10-14T17:48:56.099Z,33.11,11.62,0.01,0.00,0.01,238.57,80.78,None,2540165.0,DeAndre Hopkins,10.0,WR,1,home,left,SCREEN
339278,339278,339458,339458,339458,2018101403:1284:6,2018-10-14T17:48:56.099Z,33.17,21.34,3.51,3.19,0.37,220.51,185.93,None,2541316.0,Ryan Griffin,84.0,TE,1,home,left,SCREEN
339279,339279,339459,339459,339459,2018101403:1284:6,2018-10-14T17:48:56.099Z,26.59,31.55,0.93,0.67,0.09,124.79,168.70,None,2543851.0,Phillip Gaines,28.0,CB,1,away,left,NaN
339280,339280,339460,339460,339460,2018101403:1284:6,2018-10-14T17:48:56.099Z,31.46,13.53,0.02,0.02,0.00,266.56,344.05,None,2555346.0,Will Fuller,15.0,WR,1,home,left,FLAT
339281,339281,339461,339461,339461,2018101403:1284:6,2018-10-14T17:48:56.099Z,26.30,9.78,0.63,0.15,0.06,58.65,264.07,None,2557867.0,Tre'Davious White,27.0,CB,1,away,left,NaN
339282,339282,339462,339462,339462,2018101403:1284:6,2018-10-14T17:48:56.099Z,26.70,24.62,0.04,0.04,0.00,83.16,121.66,None,2557969.0,Matt Milano,58.0,OLB,1,away,left,NaN
339283,339283,339463,339463,339463,2018101403:1284:6,2018-10-14T17:48:56.099Z,32.25,23.84,0.02,0.02,0.01,250.80,285.07,None,2558063.0,Deshaun Watson,4.0,QB,1,home,left,NaN
339284,339284,339464,339464,339464,2018101403:1284:6,2018-10-14T17:48:56.099Z,26.63,21.28,0.10,0.08,0.04,85.49,157.28,None,2560713.0,Tremaine Edmunds,49.0,LB,1,away,left,NaN
339285,339285,339465,339465,339465,2018101403:1284:6,2018-10-14T17:48:56.099Z,31.94,28.45,0.03,0.02,0.02,244.44,86.32,None,2560896.0,Jordan Thomas,83.0,TE,1,home,left,CROSS
339286,339286,339466,339466,339466,2018101403:1284:6,2018-10-14T17:48:56.099Z,32.06,-0.85,0.32,0.94,0.03,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,left,NaN