In [1]:
import pandas as pd
import pickle

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
week1 = pd.read_csv("../processed_data/clean/week1.csv")
week2 = pd.read_csv("../processed_data/clean/week2.csv")
week3 = pd.read_csv("../processed_data/clean/week3.csv")
week4 = pd.read_csv("../processed_data/clean/week4.csv")
week5 = pd.read_csv("../processed_data/clean/week5.csv")
week6 = pd.read_csv("../processed_data/clean/week6.csv")
week7 = pd.read_csv("../processed_data/clean/week7.csv")
week8 = pd.read_csv("../processed_data/clean/week8.csv")
week9 = pd.read_csv("../processed_data/clean/week9.csv")
week10 = pd.read_csv("../processed_data/clean/week10.csv")
week11 = pd.read_csv("../processed_data/clean/week11.csv")
week12 = pd.read_csv("../processed_data/clean/week12.csv")
week13 = pd.read_csv("../processed_data/clean/week13.csv")
week14 = pd.read_csv("../processed_data/clean/week14.csv")
week15 = pd.read_csv("../processed_data/clean/week15.csv")
week16 = pd.read_csv("../processed_data/clean/week16.csv")
week17 = pd.read_csv("../processed_data/clean/week17.csv")
week1.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,level_0,Unnamed: 0.1.1.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,0,0,0,0,0,0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,1,1,1,1,1,1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2,2,2,2,2,2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,3,3,3,3,3,3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,4,4,4,4,4,4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH

In [4]:
weeks = [week1,week2,week3,week4,week5,week6,week7,week8,week9,week10,week11,week12,week13,week14,week15,week16,week17]

In [5]:
plays = pd.read_csv("../processed_data/clean/plays.csv",index_col=1)
plays.head()

,Unnamed: 0,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
id,,,,,,,,,,,,,,,,,,,,,,,,,
2018090600:75:1,0,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,I_FORM,"2 RB, 1 TE, 2 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",0.0,0.0,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False
2018090600:146:1,1,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",0.0,0.0,13:10:00,49.0,NaN,NaN,I,0,0,-0.372360,False
2018090600:168:1,2,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,SHOTGUN,"2 RB, 1 TE, 2 WR",6.0,4.0,"4 DL, 2 LB, 5 DB",0.0,0.0,13:05:00,49.0,NaN,NaN,I,0,0,-0.702779,False
2018090600:190:1,3,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,5.0,"4 DL, 1 LB, 6 DB",0.0,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False
2018090600:256:1,4,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,SHOTGUN,"2 RB, 3 TE, 0 WR",8.0,6.0,"6 DL, 3 LB, 2 DB",0.0,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False

In [6]:
games = pd.read_csv("../raw_data/games.csv",index_col=0)
games.head()

              gameDate gameTimeEastern homeTeamAbbr visitorTeamAbbr  week
gameId
2018090600  09/06/2018        20:20:00          PHI             ATL     1
2018090901  09/09/2018        13:00:00          CLE             PIT     1
2018090902  09/09/2018        13:00:00          IND             CIN     1
2018090903  09/09/2018        13:00:00          MIA             TEN     1
2018090900  09/09/2018        13:00:00          BAL             BUF     1

In [7]:
def obtainDefenseTeam(playId):
    playIdParts = playId.split(":")
    gameId = playIdParts[0]
    visitorTeam = games.loc[int(gameId)]["visitorTeamAbbr"]
    homeTeam = games.loc[int(gameId)]["homeTeamAbbr"]
    possessionTeam = plays.loc[playId]["possessionTeam"]
    
    if possessionTeam == visitorTeam: #si equipo visitante tiene el balón, el equipo local es el que defiende
        value = "home"
    elif possessionTeam == homeTeam:
        value = "away"
    
    return value

In [8]:
def obtainOffenseTeam(playId):
    playIdParts = playId.split(":")
    gameId = playIdParts[0]
    visitorTeam = games.loc[int(gameId)]["visitorTeamAbbr"]
    homeTeam = games.loc[int(gameId)]["homeTeamAbbr"]
    possessionTeam = plays.loc[playId]["possessionTeam"]
    
    if possessionTeam == visitorTeam: #si equipo visitante tiene el balón, el equipo local es el que defiende
        value = "away"
    elif possessionTeam == homeTeam:
        value = "home"
    
    return value

In [9]:
for week in weeks:
    week.drop(["Unnamed: 0","Unnamed: 0.1","Unnamed: 0.1.1","level_0","Unnamed: 0.1.1.1","index"],axis=1,inplace=True)

In [12]:
pass_rushers = {}
for week in weeks:
    for play in week["id"].unique():
        players = week[week["id"]==play]
        los = plays.loc[play]["absoluteYardlineNumber"]
        playDirection = players["playDirection"].values[0]
        players_pass_rush = []
        max_frame = -1
        if ('pass_forward' in list(week[week["id"]==play]["event"].unique())):
                max_frame = week[(week["id"]==play)&(week["event"]=='pass_forward')]["frameId"].values[0]

        for frame in range(1,max_frame+1):
            players_frame = players[(players["frameId"]==frame)&(players["team"]==obtainDefenseTeam(play))]
            for index,row in players_frame.iterrows():
                if row["displayName"] == "Football":
                    continue
                if playDirection == "right" and row["x"] < los - 2 and row["nflId"] not in players_pass_rush:
                    players_pass_rush.append(row["nflId"])
                elif playDirection == "left" and row["x"] > los + 2 and row["nflId"] not in players_pass_rush:
                    players_pass_rush.append(row["nflId"])
        pass_rushers[play] = players_pass_rush

In [13]:
#save dataset
pickle_file = open('../resources/pass_rushers.pickle','wb')
pickle.dump(pass_rushers,pickle_file)
pickle_file.close()

In [10]:
#load dataset
pickle_file = open('../resources/pass_rushers.pickle','rb')
pass_rushers = pickle.load(pickle_file)
pickle_file.close()

In [12]:
play = "2018090600:75:1"

In [13]:
pass_rushers[play]

[]

In [14]:
week1[(week1["id"]==play)&(week1["frameId"]==5)]

,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
56,2018090600:75:1,2018-09-07T01:07:15.000Z,91.73,26.65,0.00,0.00,0.01,288.28,225.38,None,310.0,Matt Ryan,2.0,QB,5,away,left,NaN
57,2018090600:75:1,2018-09-07T01:07:15.000Z,88.90,36.49,0.01,0.01,0.01,106.09,48.65,None,79848.0,Malcolm Jenkins,27.0,SS,5,home,left,NaN
58,2018090600:75:1,2018-09-07T01:07:15.000Z,91.37,44.16,0.02,0.02,0.01,290.45,38.72,None,2495454.0,Julio Jones,11.0,WR,5,away,left,HITCH
59,2018090600:75:1,2018-09-07T01:07:15.000Z,86.36,22.00,0.14,0.26,0.01,71.27,77.00,None,2495613.0,Corey Graham,24.0,FS,5,home,left,NaN
60,2018090600:75:1,2018-09-07T01:07:15.000Z,90.78,36.15,0.00,0.00,0.00,258.61,253.71,None,2533040.0,Mohamed Sanu,12.0,WR,5,away,left,HITCH
61,2018090600:75:1,2018-09-07T01:07:15.000Z,73.63,28.69,0.03,0.02,0.00,105.59,235.03,None,2534832.0,Rodney McLeod,23.0,FS,5,home,left,NaN
62,2018090600:75:1,2018-09-07T01:07:15.000Z,98.25,26.62,0.00,0.01,0.00,263.48,197.03,None,2543583.0,Devonta Freeman,24.0,RB,5,away,left,NaN
63,2018090600:75:1,2018-09-07T01:07:15.000Z,86.50,31.07,0.05,0.04,0.01,105.85,71.25,None,2552315.0,Jordan Hicks,58.0,MLB,5,home,left,NaN
64,2018090600:75:1,2018-09-07T01:07:15.000Z,82.67,20.52,0.04,0.02,0.01,84.30,172.13,None,2552689.0,Ronald Darby,21.0,CB,5,home,left,NaN
65,2018090600:75:1,2018-09-07T01:07:15.000Z,84.02,43.48,0.08,0.07,0.01,104.20,112.28,None,2555383.0,Jalen Mills,31.0,CB,5,home,left,NaN
66,2018090600:75:1,2018-09-07T01:07:15.000Z,91.28,21.84,0.01,0.01,0.00,251.59,151.96,None,2555415.0,Austin Hooper,81.0,TE,5,away,left,OUT
67,2018090600:75:1,2018-09-07T01:07:15.000Z,85.66,26.66,0.02,0.03,0.01,88.58,35.71,None,2558175.0,Nate Gerry,47.0,LB,5,home,left,NaN
68,2018090600:75:1,2018-09-07T01:07:15.000Z,95.12,26.71,0.00,0.01,0.00,248.81,242.73,None,2559033.0,Ricky Ortiz,30.0,FB,5,away,left,FLAT
69,2018090600:75:1,2018-09-07T01:07:15.000Z,90.11,26.85,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,5,football,left,NaN

In [15]:
week1[(week1["nflId"].isin(list(pass_rushers[play])))&(week1["id"]==play)]

Empty DataFrame
Columns: [id, time, x, y, s, a, dis, o, dir, event, nflId, displayName, jerseyNumber, position, frameId, team, playDirection, route]
Index: []

In [16]:
week1.drop(week1[(week1["id"]==play)&(week1["nflId"].isin(pass_rushers[play]))].index)

,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982201,2018091001:4192:1,2018-09-11T05:29:39.900Z,33.68,43.14,1.96,3.79,0.22,281.35,309.70,None,2556277.0,Marqui Christian,41.0,SS,65,away,left,NaN
982202,2018091001:4192:1,2018-09-11T05:29:39.900Z,36.02,40.21,0.81,1.52,0.09,308.07,234.06,None,2556593.0,Cory Littleton,58.0,ILB,65,away,left,NaN
982203,2018091001:4192:1,2018-09-11T05:29:39.900Z,33.02,43.81,2.63,4.57,0.27,183.83,314.39,None,2556885.0,Jalen Richard,30.0,RB,65,home,left,SCREEN
982204,2018091001:4192:1,2018-09-11T05:29:39.900Z,34.13,40.86,0.15,0.72,0.02,6.17,267.87,None,2558183.0,John Johnson,43.0,SS,65,away,left,NaN
982205,2018091001:4192:1,2018-09-11T05:29:39.900Z,33.29,43.92,1.81,4.24,0.20,NaN,NaN,None,NaN,Football,NaN,NaN,65,football,left,NaN

In [17]:
for play in pass_rushers:
    #print(play)
    idParts = play.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    #print(pass_rushers[play])
    week.drop(week[(week["id"]==play)&(week["nflId"].isin(pass_rushers[play]))].index,inplace=True)

In [19]:
week_number = 1
for week in weeks:
    week.to_csv("../processed_data/clean_without_pass_rushers/week{}.csv".format(week_number))
    week_number+=1