In [2]:
import pandas as pd
import pickle

#Para el Ã¡rea
from shapely.geometry import Polygon
from shapely.geometry import MultiPoint 
from scipy.spatial import ConvexHull
from shapely.geometry import LineString
from shapely.geometry.point import Point

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
week1 = pd.read_csv("../processed_data/clean_without_pass_rushers/week1.csv")
week2 = pd.read_csv("../processed_data/clean_without_pass_rushers/week2.csv")
week3 = pd.read_csv("../processed_data/clean_without_pass_rushers/week3.csv")
week4 = pd.read_csv("../processed_data/clean_without_pass_rushers/week4.csv")
week5 = pd.read_csv("../processed_data/clean_without_pass_rushers/week5.csv")
week6 = pd.read_csv("../processed_data/clean_without_pass_rushers/week6.csv")
week7 = pd.read_csv("../processed_data/clean_without_pass_rushers/week7.csv")
week8 = pd.read_csv("../processed_data/clean_without_pass_rushers/week8.csv")
week9 = pd.read_csv("../processed_data/clean_without_pass_rushers/week9.csv")
week10 = pd.read_csv("../processed_data/clean_without_pass_rushers/week10.csv")
week11 = pd.read_csv("../processed_data/clean_without_pass_rushers/week11.csv")
week12 = pd.read_csv("../processed_data/clean_without_pass_rushers/week12.csv")
week13 = pd.read_csv("../processed_data/clean_without_pass_rushers/week13.csv")
week14 = pd.read_csv("../processed_data/clean_without_pass_rushers/week14.csv")
week15 = pd.read_csv("../processed_data/clean_without_pass_rushers/week15.csv")
week16 = pd.read_csv("../processed_data/clean_without_pass_rushers/week16.csv")
week17 = pd.read_csv("../processed_data/clean_without_pass_rushers/week17.csv")
week1.head()

,Unnamed: 0,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH

In [4]:
weeks = [week1,week2,week3,week4,week5,week6,week7,week8,week9,week10,week11,week12,week13,week14,week15,week16,week17]

In [5]:
for week in weeks:
    week.drop(["Unnamed: 0"],axis=1,inplace=True)

In [6]:
static_defense = pd.read_csv("../transformed_data/static_defenses_yards.csv",index_col=1)
static_defense.head()

,Unnamed: 0,defensivelinezonePlayers,deepzonePlayers,hookzonePlayers,curlzonePlayers,flatzonePlayers,defenseArea,defenseAreaCoverDefenders,width,height,numberQBs,numberWRs,numberTEs,numberRBs,numberFBs,numberOffensivePlayersAnotherPosition,numberSafeties,numberLBs,numberCBs,strongSide,numberPlayersDefenseStrongSide,numberPlayersDefenseWeakSide,numberPlayersOffenseStrongSide,numberPlayersOffenseWeakSide,differenceOffenseVsDefenseWidth,differenceOffenseVsDefenseStrongSide,differenceOffenseVsDefenseWeakSide,HeightByWeightDeep,HeightByWeightHook,HeightByWeightCurl,HeightByWeightFlat,WeightByArea,density,densityNoLine,densityInsidePoints,densityInsidePointsNoLine,playResult
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018090600:75:1,0,0,1,3,2,1,194.31095,194.31095,22.96,15.25,1,2,1,1,1,0,3,2,2,left,3,4,3,2,-0.63,0,-2,0.020227,0.018643,0.020066,0.021034,3.376032,0.036025,0.036025,6.974268,6.974268,10
2018090600:146:1,1,0,1,3,2,1,204.17725,204.17725,29.22,12.57,1,3,1,1,0,0,2,2,3,right,3,4,2,3,-1.15,-1,-1,0.020227,0.019228,0.020356,0.020455,3.178611,0.034284,0.034284,6.975511,6.975511,0
2018090600:168:1,2,0,1,2,2,2,277.65495,277.65495,33.67,15.21,1,2,1,2,0,0,2,2,3,left,5,2,4,1,0.71,-1,-1,0.020227,0.017683,0.020997,0.020745,2.337434,0.025211,0.025211,6.985594,6.985594,0
2018090600:190:1,3,1,0,2,3,1,189.16960,165.05520,26.42,12.91,1,3,1,1,0,0,3,1,3,right,2,5,2,3,-3.11,0,-2,0.000000,0.020120,0.021193,0.020455,3.192871,0.037004,0.036351,6.973569,6.969707,33
2018090600:320:1,5,1,0,3,3,1,187.12510,153.20020,27.80,13.29,1,3,1,1,0,0,2,3,3,left,3,5,3,2,-4.82,0,-3,0.000000,0.018995,0.019537,0.021279,4.281979,0.042752,0.045692,7.978624,7.980418,4

In [7]:
static_defense.drop(["Unnamed: 0"],axis=1,inplace=True)

In [4]:
plays = pd.read_csv("../processed_data/clean/plays.csv",index_col=1)
plays.head()

,Unnamed: 0,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,...,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
id,,,,,,,,,,,,,,,,,,,,,
2018090600:75:1,0,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,I_FORM,...,0.0,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False
2018090600:146:1,1,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,SINGLEBACK,...,0.0,13:10:00,49.0,NaN,NaN,I,0,0,-0.372360,False
2018090600:168:1,2,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,SHOTGUN,...,0.0,13:05:00,49.0,NaN,NaN,I,0,0,-0.702779,False
2018090600:190:1,3,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,SHOTGUN,...,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False
2018090600:256:1,4,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,SHOTGUN,...,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False

In [5]:
plays.drop(["Unnamed: 0"],axis=1,inplace=True)

In [6]:
def obtainDefenseTeam(playId):
    playIdParts = playId.split(":")
    gameId = playIdParts[0]
    visitorTeam = games.loc[int(gameId)]["visitorTeamAbbr"]
    homeTeam = games.loc[int(gameId)]["homeTeamAbbr"]
    possessionTeam = plays.loc[playId]["possessionTeam"]
    
    if possessionTeam == visitorTeam: #si equipo visitante tiene el balÃ³n, el equipo local es el que defiende
        value = "home"
    elif possessionTeam == homeTeam:
        value = "away"
    
    return value

In [7]:
def obtainOffenseTeam(playId):
    playIdParts = playId.split(":")
    gameId = playIdParts[0]
    visitorTeam = games.loc[int(gameId)]["visitorTeamAbbr"]
    homeTeam = games.loc[int(gameId)]["homeTeamAbbr"]
    possessionTeam = plays.loc[playId]["possessionTeam"]
    
    if possessionTeam == visitorTeam: #si equipo visitante tiene el balÃ³n, el equipo local es el que defiende
        value = "away"
    elif possessionTeam == homeTeam:
        value = "home"
    
    return value

In [8]:
games = pd.read_csv("../raw_data/games.csv",index_col=0)
games.head()

              gameDate gameTimeEastern homeTeamAbbr visitorTeamAbbr  week
gameId
2018090600  09/06/2018        20:20:00          PHI             ATL     1
2018090901  09/09/2018        13:00:00          CLE             PIT     1
2018090902  09/09/2018        13:00:00          IND             CIN     1
2018090903  09/09/2018        13:00:00          MIA             TEN     1
2018090900  09/09/2018        13:00:00          BAL             BUF     1

In [13]:
summary = pd.DataFrame()

# Obtener todas las jugadas de tercer down

In [14]:
third_down_plays = plays[(plays["down"]==3)&(plays["passResult"]!="S")]
third_down_plays

,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
id,,,,,,,,,,,,,,,,,,,,,,,,
2018090600:190:1,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,5.0,"4 DL, 1 LB, 6 DB",0.0,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False
2018090600:256:1,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,SHOTGUN,"2 RB, 3 TE, 0 WR",8.0,6.0,"6 DL, 3 LB, 2 DB",0.0,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False
2018090600:344:1,(9:24) (Shotgun) N.Foles pass incomplete short...,1,3,4,PHI,play_type_pass,PHI,8,EMPTY,"1 RB, 2 TE, 2 WR",6.0,4.0,"3 DL, 3 LB, 5 DB",0.0,0.0,09:24:00,18.0,NaN,NaN,I,0,0,-1.192208,False
2018090600:636:1,(5:07) (Shotgun) M.Ryan pass incomplete short ...,1,3,3,ATL,play_type_pass,PHI,3,SHOTGUN,"1 RB, 2 TE, 2 WR",6.0,4.0,"4 DL, 2 LB, 5 DB",0.0,0.0,05:07:00,13.0,NaN,NaN,I,0,0,-0.874640,False
2018090600:949:1,(15:00) (Shotgun) M.Ryan pass short left to D....,2,3,12,ATL,play_type_pass,ATL,18,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,4.0,"4 DL, 1 LB, 6 DB",3.0,0.0,15:00:00,28.0,NaN,NaN,C,-7,-7,-1.912483,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018123015:2373:17,(11:58) (Shotgun) J.Rosen pass incomplete shor...,3,3,2,ARI,play_type_pass,ARI,27,EMPTY,"1 RB, 1 TE, 3 WR",5.0,4.0,"4 DL, 2 LB, 5 DB",13.0,14.0,11:58:00,37.0,NaN,NaN,I,0,0,-1.659557,False
2018123015:2629:17,(7:43) (Shotgun) J.Rosen pass incomplete deep ...,3,3,13,ARI,play_type_pass,SEA,48,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,4.0,"4 DL, 1 LB, 6 DB",13.0,14.0,07:43:00,62.0,NaN,NaN,I,0,0,-1.748119,False
2018123015:2998:17,(4:17) (Shotgun) J.Rosen pass short middle to ...,3,3,10,ARI,play_type_pass,ARI,30,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,4.0,"4 DL, 1 LB, 6 DB",13.0,21.0,04:17:00,40.0,NaN,NaN,C,9,9,-1.153889,False
2018123015:3180:17,(:24) (Shotgun) R.Wilson pass incomplete short...,3,3,5,SEA,play_type_pass,SEA,25,EMPTY,"1 RB, 1 TE, 3 WR",7.0,5.0,"4 DL, 2 LB, 5 DB",13.0,21.0,00:24:00,85.0,NaN,NaN,I,0,0,-1.617042,False
2018123015:3969:17,(2:00) (Shotgun) J.Rosen pass incomplete deep ...,4,3,12,ARI,play_type_pass,SEA,37,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,4.0,"4 DL, 1 LB, 6 DB",21.0,24.0,02:00:00,47.0,NaN,NaN,I,0,0,-0.944168,False

In [15]:
def evaluateDefense(playId):
    yardsToGo = third_down_plays.loc[playId]["yardsToGo"]
    offensePlayResult = third_down_plays.loc[playId]["offensePlayResult"]
    
    if offensePlayResult < yardsToGo:
        value = 1   #defensa exitosa
    else:
        value = 0   #mala defensa
        
    return value

In [16]:
third_down_plays["defenseValoration"] = third_down_plays.index.map(evaluateDefense)
third_down_plays.head()

<ipython-input-16-50b5a2e6bb80>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  third_down_plays["defenseValoration"] = third_down_plays.index.map(evaluateDefense)

,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI,defenseValoration
id,,,,,,,,,,,,,,,,,,,,,,,,,
2018090600:190:1,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,5.0,"4 DL, 1 LB, 6 DB",0.0,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False,0
2018090600:256:1,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,SHOTGUN,"2 RB, 3 TE, 0 WR",8.0,6.0,"6 DL, 3 LB, 2 DB",0.0,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False,1
2018090600:344:1,(9:24) (Shotgun) N.Foles pass incomplete short...,1,3,4,PHI,play_type_pass,PHI,8,EMPTY,"1 RB, 2 TE, 2 WR",6.0,4.0,"3 DL, 3 LB, 5 DB",0.0,0.0,09:24:00,18.0,NaN,NaN,I,0,0,-1.192208,False,1
2018090600:636:1,(5:07) (Shotgun) M.Ryan pass incomplete short ...,1,3,3,ATL,play_type_pass,PHI,3,SHOTGUN,"1 RB, 2 TE, 2 WR",6.0,4.0,"4 DL, 2 LB, 5 DB",0.0,0.0,05:07:00,13.0,NaN,NaN,I,0,0,-0.874640,False,1
2018090600:949:1,(15:00) (Shotgun) M.Ryan pass short left to D....,2,3,12,ATL,play_type_pass,ATL,18,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,4.0,"4 DL, 1 LB, 6 DB",3.0,0.0,15:00:00,28.0,NaN,NaN,C,-7,-7,-1.912483,False,1

In [17]:
len(third_down_plays[third_down_plays["defenseValoration"]==0])

1787

In [18]:
len(third_down_plays[third_down_plays["defenseValoration"]==1])

2768

In [19]:
summary["playId"]= third_down_plays.index

In [20]:
summary

                  playId
0       2018090600:190:1
1       2018090600:256:1
2       2018090600:344:1
3       2018090600:636:1
4       2018090600:949:1
...                  ...
4550  2018123015:2373:17
4551  2018123015:2629:17
4552  2018123015:2998:17
4553  2018123015:3180:17
4554  2018123015:3969:17

[4555 rows x 1 columns]

Obtener los jugadores defensivos de esa jugada:

# Complex Features (c): CaracterÃ­sticas dinÃ¡micas de la acciÃ³n en general. Posiblemente podrÃ­a ser cosas como variaciÃ³n de la superficie cubierta, variaciÃ³n de densidad, defensores en la zona del pase, ....

In [22]:
def obtainAreaDefense(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    #print(playId)
    try:
        fpf_number = week[(week["id"]==playId) & (week["event"]=="pass_forward")]["frameId"].values[0]
    except:
        fpf_number = week[(week["id"]==playId) & (week["event"]=="pass_shovel")]["frameId"].values[0]
    
    defenders = week[(week["team"]==obtainDefenseTeam(playId))&(week["id"]==playId)&(week["frameId"]==fpf_number)]
    position_players = []
    playDirection = defenders["playDirection"].values[0]
    los = plays.loc[playId]["absoluteYardlineNumber"]
    
    for index,row in defenders.iterrows():
        if row["position"] in ["DL","NT","DT","DE"]:
            continue
        
        if playDirection == "right" and row["x"] < los:
            continue
        elif playDirection == "left" and row["x"] > los:
            #print(row["displayName"])
            continue
        
        position_players.append((row["x"],row["y"]))
        
    #print(position_players,fpf_number)
    hull = ConvexHull(position_players)
    
    return hull.volume

In [23]:
week11[(week11["id"]=="2018111803:300:11")&(week11["event"]=="pass_forward")&(week11["team"]=="home")]

,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
266298,2018111803:300:11,2018-11-18T18:10:52.299Z,12.12,28.85,1.32,1.57,0.12,109.21,307.69,pass_forward,71441.0,Glover Quin,27.0,FS,34,home,left,NaN
266301,2018111803:300:11,2018-11-18T18:10:52.299Z,11.17,22.16,3.68,0.36,0.37,149.85,167.37,pass_forward,2543869.0,Devon Kennard,42.0,OLB,34,home,left,NaN
266302,2018111803:300:11,2018-11-18T18:10:52.299Z,11.22,26.85,1.98,2.69,0.21,147.49,132.51,pass_forward,2550572.0,Christian Jones,52.0,ILB,34,home,left,NaN
266303,2018111803:300:11,2018-11-18T18:10:52.299Z,12.21,26.41,1.35,3.05,0.13,191.57,209.77,pass_forward,2552262.0,Quandre Diggs,28.0,CB,34,home,left,NaN
266305,2018111803:300:11,2018-11-18T18:10:52.299Z,9.00,25.50,1.64,5.55,0.14,329.27,188.61,pass_forward,2557855.0,Jarrad Davis,40.0,MLB,34,home,left,NaN
266306,2018111803:300:11,2018-11-18T18:10:52.299Z,12.95,16.75,4.25,0.51,0.42,259.81,180.78,pass_forward,2557924.0,Jalen Reeves-Maybin,44.0,OLB,34,home,left,NaN

esta jugada se tiene que eliminar

In [24]:
summary.drop(summary[summary["playId"]=="2018111803:300:11"].index,inplace=True)

In [25]:
summary.drop(summary[summary["playId"]=="2018111806:4056:11"].index,inplace=True)

In [26]:
summary.drop(summary[summary["playId"]=="2018123007:3322:17"].index,inplace=True)

In [27]:
summary["areaDifference"] = summary["playId"].apply(obtainAreaDefense)

In [28]:
summary

                  playId  areaDifference
0       2018090600:190:1       244.99510
1       2018090600:256:1        26.74595
2       2018090600:344:1       224.07605
3       2018090600:636:1        90.98445
4       2018090600:949:1       193.91940
...                  ...             ...
4550  2018123015:2373:17       203.89665
4551  2018123015:2629:17       431.90245
4552  2018123015:2998:17       193.68370
4553  2018123015:3180:17       173.69860
4554  2018123015:3969:17       597.27275

[4552 rows x 2 columns]

In [29]:
#save dataset
pickle_file = open('../resources/summary_teams.pickle','wb')
pickle.dump(summary,pickle_file)
pickle_file.close()

In [32]:
dif = list(set(summary["playId"].unique()) - set(static_defense[static_defense.index.isin(summary["playId"].unique())].index))
len(dif)

703

In [33]:
summary.drop(summary[summary["playId"].isin(dif)].index,inplace=True)

In [34]:
def obtainAreaDefenseDifference(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    area1 = summary[(summary["playId"]==playId)]["areaDifference"].values[0]
    area2 = static_defense.loc[playId]["defenseArea"]
    
    return area1 - area2

In [35]:
summary["areaDifference"] = summary["playId"].apply(obtainAreaDefenseDifference)

In [36]:
summary

                  playId  areaDifference
0       2018090600:190:1        55.82550
2       2018090600:344:1         7.82150
4       2018090600:949:1        64.43250
5      2018090600:1037:1       164.09500
8      2018090600:1801:1       126.91500
...                  ...             ...
4550  2018123015:2373:17       -51.20585
4551  2018123015:2629:17       244.93410
4552  2018123015:2998:17       -72.03590
4553  2018123015:3180:17       -55.66760
4554  2018123015:3969:17       303.87530

[3849 rows x 2 columns]

In [37]:
#save dataset
pickle_file = open('../resources/summary_teams.pickle','wb')
pickle.dump(summary,pickle_file)
pickle_file.close()

In [38]:
def calculateNumberDeepPlayers(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    los = plays.loc[playId]["absoluteYardlineNumber"]
    try:
        fpf_number = week[(week["id"]==playId) & (week["event"]=="pass_forward")]["frameId"].values[0]
    except:
        fpf_number = week[(week["id"]==playId) & (week["event"]=="pass_shovel")]["frameId"].values[0]
        
    defenders = week[(week["team"]==obtainDefenseTeam(playId))&(week["id"]==playId)&(week["frameId"]==fpf_number)]
    playDirection = defenders["playDirection"].values[0]
    deepzone = -1
    
    if playDirection == "right":
        deepzone = los + 15
    elif playDirection == "left":
        deepzone = los - 15
        
    number_players=0
    for index,row in defenders.iterrows():
        if row["position"] in ["DL","NT","DT","DE"]: #muy dificil que pase, pero por si acaso
            continue
        player_x = row["x"]
        if playDirection == "right" and player_x > deepzone:
            number_players+=1
        elif playDirection == "left" and player_x < deepzone:
            number_players+=1
            
    return number_players

In [39]:
summary["numberPlayersDeep"] = summary["playId"].apply(calculateNumberDeepPlayers)

In [17]:
def obtainDeepDifference(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    deep1 = summary[(summary["playId"]==playId)]["numberPlayersDeep"].values[0]
    deep2 = static_defense.loc[playId]["deepzonePlayers"]
    
    return deep1 - deep2

In [41]:
summary

                  playId  areaDifference  numberPlayersDeep
0       2018090600:190:1        55.82550                  1
2       2018090600:344:1         7.82150                  1
4       2018090600:949:1        64.43250                  1
5      2018090600:1037:1       164.09500                  2
8      2018090600:1801:1       126.91500                  1
...                  ...             ...                ...
4550  2018123015:2373:17       -51.20585                  1
4551  2018123015:2629:17       244.93410                  2
4552  2018123015:2998:17       -72.03590                  1
4553  2018123015:3180:17       -55.66760                  0
4554  2018123015:3969:17       303.87530                  4

[3849 rows x 3 columns]

In [42]:
#save dataset
pickle_file = open('../resources/summary_teams.pickle','wb')
pickle.dump(summary,pickle_file)
pickle_file.close()

In [18]:
summary["numberPlayersDeepDifference"] =  summary["playId"].apply(obtainDeepDifference)

In [19]:
summary

,playId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference
0,2018090600:190:1,55.82550,1,1
2,2018090600:344:1,7.82150,1,1
4,2018090600:949:1,64.43250,1,1
5,2018090600:1037:1,164.09500,2,1
8,2018090600:1801:1,126.91500,1,0
...,...,...,...,...
4550,2018123015:2373:17,-51.20585,1,1
4551,2018123015:2629:17,244.93410,2,2
4552,2018123015:2998:17,-72.03590,1,1
4553,2018123015:3180:17,-55.66760,0,0
4554,2018123015:3969:17,303.87530,4,3

In [14]:
#load dataset
pickle_file = open('../resources/summary_teams.pickle','rb')
summary = pickle.load(pickle_file)
pickle_file.close()

In [20]:
def calculateNumberUnderneath(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    los = plays.loc[playId]["absoluteYardlineNumber"]
    try:
        fpf_number = week[(week["id"]==playId) & (week["event"]=="pass_forward")]["frameId"].values[0]
    except:
        fpf_number = week[(week["id"]==playId) & (week["event"]=="pass_shovel")]["frameId"].values[0]
        
    defenders = week[(week["team"]==obtainDefenseTeam(playId))&(week["id"]==playId)&(week["frameId"]==fpf_number)]
    playDirection = defenders["playDirection"].values[0]
    deepzone = -1
    
    if playDirection == "right":
        deepzone = los + 15
    elif playDirection == "left":
        deepzone = los - 15
        
    number_players=0
    for index,row in defenders.iterrows():
        if row["position"] in ["DL","NT","DT","DE"]: #muy dificil que pase, pero por si acaso
            continue
        player_x = row["x"]
        if playDirection == "right" and player_x < deepzone and player_x > los:
            number_players+=1
        elif playDirection == "left" and player_x > deepzone and player_x < los:
            number_players+=1
            
    return number_players

In [21]:
summary["numberPlayersUnderneath"] = summary["playId"].apply(calculateNumberUnderneath)

In [22]:
summary

,playId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath
0,2018090600:190:1,55.82550,1,1,5
2,2018090600:344:1,7.82150,1,1,6
4,2018090600:949:1,64.43250,1,1,6
5,2018090600:1037:1,164.09500,2,1,4
8,2018090600:1801:1,126.91500,1,0,6
...,...,...,...,...,...
4550,2018123015:2373:17,-51.20585,1,1,5
4551,2018123015:2629:17,244.93410,2,2,5
4552,2018123015:2998:17,-72.03590,1,1,5
4553,2018123015:3180:17,-55.66760,0,0,6
4554,2018123015:3969:17,303.87530,4,3,3

In [24]:
#save dataset
pickle_file = open('../resources/summary_teams.pickle','wb')
pickle.dump(summary,pickle_file)
pickle_file.close()

In [25]:
summary["densityDifference"] = (summary["numberPlayersDeep"] + summary["numberPlayersUnderneath"])/summary["areaDifference"]

In [26]:
summary

,playId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath,densityDifference
0,2018090600:190:1,55.82550,1,1,5,0.107478
2,2018090600:344:1,7.82150,1,1,6,0.894969
4,2018090600:949:1,64.43250,1,1,6,0.108641
5,2018090600:1037:1,164.09500,2,1,4,0.036564
8,2018090600:1801:1,126.91500,1,0,6,0.055155
...,...,...,...,...,...,...
4550,2018123015:2373:17,-51.20585,1,1,5,-0.117174
4551,2018123015:2629:17,244.93410,2,2,5,0.028579
4552,2018123015:2998:17,-72.03590,1,1,5,-0.083292
4553,2018123015:3180:17,-55.66760,0,0,6,-0.107783
4554,2018123015:3969:17,303.87530,4,3,3,0.023036

In [27]:
def calculateHeight(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    try:
        fpf_number = week[(week["id"]==playId) & (week["event"]=="pass_forward")]["frameId"].values[0]
    except:
        fpf_number = week[(week["id"]==playId) & (week["event"]=="pass_shovel")]["frameId"].values[0]
        
    defenders = week[(week["team"]==obtainDefenseTeam(playId))&(week["id"]==playId)&(week["frameId"]==fpf_number)]
    playDirection = defenders["playDirection"].values[0]
    los = plays.loc[playId]["absoluteYardlineNumber"]
    
    players_x = []
    
    for index,row in defenders.iterrows():
        if playDirection == "right" and los < row["x"]:
            players_x.append(row["x"])
        elif playDirection == "left" and los > row["x"]:
            players_x.append(row["x"])
        
    return abs(max(players_x) - min(players_x))

In [28]:
summary["heightDifference"] = summary["playId"].apply(calculateHeight)

In [29]:
summary

,playId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath,densityDifference,heightDifference
0,2018090600:190:1,55.82550,1,1,5,0.107478,15.67
2,2018090600:344:1,7.82150,1,1,6,0.894969,11.43
4,2018090600:949:1,64.43250,1,1,6,0.108641,9.53
5,2018090600:1037:1,164.09500,2,1,4,0.036564,20.34
8,2018090600:1801:1,126.91500,1,0,6,0.055155,17.80
...,...,...,...,...,...,...,...
4550,2018123015:2373:17,-51.20585,1,1,5,-0.117174,15.44
4551,2018123015:2629:17,244.93410,2,2,5,0.028579,20.44
4552,2018123015:2998:17,-72.03590,1,1,5,-0.083292,19.02
4553,2018123015:3180:17,-55.66760,0,0,6,-0.107783,7.24
4554,2018123015:3969:17,303.87530,4,3,3,0.023036,22.57

In [30]:
#save dataset
pickle_file = open('../resources/summary_teams.pickle','wb')
pickle.dump(summary,pickle_file)
pickle_file.close()

In [31]:
def obtainHeightDifference(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    height1 = summary[(summary["playId"]==playId)]["heightDifference"].values[0]
    height2 = static_defense.loc[playId]["height"]
    
    return height1 - height2

In [32]:
summary["heightDifference"] =  summary["playId"].apply(obtainHeightDifference)

In [33]:
summary

,playId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath,densityDifference,heightDifference
0,2018090600:190:1,55.82550,1,1,5,0.107478,2.76
2,2018090600:344:1,7.82150,1,1,6,0.894969,-0.36
4,2018090600:949:1,64.43250,1,1,6,0.108641,1.64
5,2018090600:1037:1,164.09500,2,1,4,0.036564,5.41
8,2018090600:1801:1,126.91500,1,0,6,0.055155,2.64
...,...,...,...,...,...,...,...
4550,2018123015:2373:17,-51.20585,1,1,5,-0.117174,2.10
4551,2018123015:2629:17,244.93410,2,2,5,0.028579,8.79
4552,2018123015:2998:17,-72.03590,1,1,5,-0.083292,5.48
4553,2018123015:3180:17,-55.66760,0,0,6,-0.107783,-3.37
4554,2018123015:3969:17,303.87530,4,3,3,0.023036,7.90

In [34]:
def calculateWidth(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    try:
        fpf_number = week[(week["id"]==playId) & (week["event"]=="pass_forward")]["frameId"].values[0]
    except:
        fpf_number = week[(week["id"]==playId) & (week["event"]=="pass_shovel")]["frameId"].values[0]
        
    defenders = week[(week["team"]==obtainDefenseTeam(playId))&(week["id"]==playId)&(week["frameId"]==fpf_number)]
    playDirection = defenders["playDirection"].values[0]
    los = plays.loc[playId]["absoluteYardlineNumber"]
    
    players_y = []
    
    for index,row in defenders.iterrows():
        if playDirection == "right" and los < row["x"]:
            players_y.append(row["y"])
        elif playDirection == "left" and los > row["x"]:
            players_y.append(row["y"])
        
    return max(players_y) - min(players_y)

In [35]:
summary["widthDifference"] = summary["playId"].apply(calculateWidth)

In [36]:
summary

,playId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath,densityDifference,heightDifference,widthDifference
0,2018090600:190:1,55.82550,1,1,5,0.107478,2.76,31.04
2,2018090600:344:1,7.82150,1,1,6,0.894969,-0.36,37.25
4,2018090600:949:1,64.43250,1,1,6,0.108641,1.64,34.78
5,2018090600:1037:1,164.09500,2,1,4,0.036564,5.41,25.21
8,2018090600:1801:1,126.91500,1,0,6,0.055155,2.64,36.78
...,...,...,...,...,...,...,...,...
4550,2018123015:2373:17,-51.20585,1,1,5,-0.117174,2.10,31.39
4551,2018123015:2629:17,244.93410,2,2,5,0.028579,8.79,32.00
4552,2018123015:2998:17,-72.03590,1,1,5,-0.083292,5.48,25.33
4553,2018123015:3180:17,-55.66760,0,0,6,-0.107783,-3.37,38.03
4554,2018123015:3969:17,303.87530,4,3,3,0.023036,7.90,42.64

In [37]:
#save dataset
pickle_file = open('../resources/summary_teams.pickle','wb')
pickle.dump(summary,pickle_file)
pickle_file.close()

In [40]:
def obtainWidthDifference(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    width1 = summary[(summary["playId"]==playId)]["widthDifference"].values[0]
    width2 = static_defense.loc[playId]["width"]
    
    return width1 - width2

In [41]:
summary["widthDifference"] =  summary["playId"].apply(obtainHeightDifference)

In [42]:
summary

,playId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath,densityDifference,heightDifference,widthDifference
0,2018090600:190:1,55.82550,1,1,5,0.107478,2.76,-10.15
2,2018090600:344:1,7.82150,1,1,6,0.894969,-0.36,-12.15
4,2018090600:949:1,64.43250,1,1,6,0.108641,1.64,-6.25
5,2018090600:1037:1,164.09500,2,1,4,0.036564,5.41,-9.52
8,2018090600:1801:1,126.91500,1,0,6,0.055155,2.64,-12.52
...,...,...,...,...,...,...,...,...
4550,2018123015:2373:17,-51.20585,1,1,5,-0.117174,2.10,-11.24
4551,2018123015:2629:17,244.93410,2,2,5,0.028579,8.79,-2.86
4552,2018123015:2998:17,-72.03590,1,1,5,-0.083292,5.48,-8.06
4553,2018123015:3180:17,-55.66760,0,0,6,-0.107783,-3.37,-13.98
4554,2018123015:3969:17,303.87530,4,3,3,0.023036,7.90,-6.77

# se pueden aÃ±adir las caracterÃ­sticas estÃ¡ticas del comienzo o el cluster.

In [43]:
clusters = pd.read_csv("../unsupervised_datasets/kmeans/static_defenses_rs_kmeans_without_outliers.csv",index_col="id")
clusters.head()

,defensivelinezonePlayers,deepzonePlayers,hookzonePlayers,curlzonePlayers,flatzonePlayers,defenseArea,defenseAreaCoverDefenders,width,height,numberQBs,numberWRs,numberTEs,numberRBs,numberFBs,numberOffensivePlayersAnotherPosition,numberSafeties,numberLBs,numberCBs,strongSide,numberPlayersDefenseStrongSide,numberPlayersDefenseWeakSide,numberPlayersOffenseStrongSide,numberPlayersOffenseWeakSide,differenceOffenseVsDefenseWidth,differenceOffenseVsDefenseStrongSide,differenceOffenseVsDefenseWeakSide,HeightByWeightDeep,HeightByWeightHook,HeightByWeightCurl,HeightByWeightFlat,WeightByArea,density,densityNoLine,densityInsidePoints,densityInsidePointsNoLine,cluster
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018090600:75:1,0,1,3,2,1,194.31095,194.31095,22.96,15.25,1,2,1,1,1,0,3,2,2,1,3,4,3,2,-0.63,0,-2,0.020227,0.018643,0.020066,0.021034,3.376032,0.036025,0.036025,6.974268,6.974268,0
2018090600:146:1,0,1,3,2,1,204.17725,204.17725,29.22,12.57,1,3,1,1,0,0,2,2,3,0,3,4,2,3,-1.15,-1,-1,0.020227,0.019228,0.020356,0.020455,3.178611,0.034284,0.034284,6.975511,6.975511,0
2018090600:168:1,0,1,2,2,2,277.65495,277.65495,33.67,15.21,1,2,1,2,0,0,2,2,3,1,5,2,4,1,0.71,-1,-1,0.020227,0.017683,0.020997,0.020745,2.337434,0.025211,0.025211,6.985594,6.985594,0
2018090600:190:1,1,0,2,3,1,189.16960,165.05520,26.42,12.91,1,3,1,1,0,0,3,1,3,0,2,5,2,3,-3.11,0,-2,0.000000,0.020120,0.021193,0.020455,3.192871,0.037004,0.036351,6.973569,6.969707,0
2018090600:320:1,1,0,3,3,1,187.12510,153.20020,27.80,13.29,1,3,1,1,0,0,2,3,3,1,3,5,3,2,-4.82,0,-3,0.000000,0.018995,0.019537,0.021279,4.281979,0.042752,0.045692,7.978624,7.980418,0

In [44]:
clusters["cluster"].unique()

array([0, 1, 2])

In [47]:
dif = list(set(summary["playId"].unique()) - set(clusters[clusters.index.isin(summary["playId"].unique())].index))
len(dif)

31

In [48]:
summary.drop(summary[summary["playId"].isin(dif)].index,inplace=True)

In [49]:
def obtainCluster(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    return clusters.loc[playId]["cluster"]

In [50]:
summary["cluster"] = summary["playId"].apply(obtainCluster)

In [51]:
summary

,playId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath,densityDifference,heightDifference,widthDifference,cluster
0,2018090600:190:1,55.82550,1,1,5,0.107478,2.76,-10.15,0.0
2,2018090600:344:1,7.82150,1,1,6,0.894969,-0.36,-12.15,0.0
4,2018090600:949:1,64.43250,1,1,6,0.108641,1.64,-6.25,0.0
5,2018090600:1037:1,164.09500,2,1,4,0.036564,5.41,-9.52,1.0
8,2018090600:1801:1,126.91500,1,0,6,0.055155,2.64,-12.52,0.0
...,...,...,...,...,...,...,...,...,...
4550,2018123015:2373:17,-51.20585,1,1,5,-0.117174,2.10,-11.24,0.0
4551,2018123015:2629:17,244.93410,2,2,5,0.028579,8.79,-2.86,0.0
4552,2018123015:2998:17,-72.03590,1,1,5,-0.083292,5.48,-8.06,0.0
4553,2018123015:3180:17,-55.66760,0,0,6,-0.107783,-3.37,-13.98,0.0
4554,2018123015:3969:17,303.87530,4,3,3,0.023036,7.90,-6.77,0.0

# Game context features(g): down, score ...

In [52]:
def obtainHomeScore(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    return plays.loc[playId]["preSnapHomeScore"]

In [53]:
summary["homeScore"] = summary["playId"].apply(obtainHomeScore)

In [54]:
def obtainVisitorScore(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    return plays.loc[playId]["preSnapVisitorScore"]

In [55]:
summary["visitorScore"] = summary["playId"].apply(obtainVisitorScore)

In [56]:
def obtainDown(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    return plays.loc[playId]["down"]

In [57]:
summary["down"] = summary["playId"].apply(obtainDown)

In [58]:
def obtainQuarter(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    return plays.loc[playId]["quarter"]

In [59]:
summary["quarter"] = summary["playId"].apply(obtainQuarter)

In [60]:
def obtainYardsToGo(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    return plays.loc[playId]["yardsToGo"]

In [61]:
summary["yardsToGo"] = summary["playId"].apply(obtainYardsToGo)

In [62]:
def obtainYardsToEndZone(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    absoluteYard = plays.loc[playId]["absoluteYardlineNumber"]
    defense = week[(week["team"]==obtainDefenseTeam(playId))&(week["id"]==playId)]
    direction = defense["playDirection"].values[0]
    
    if direction == "right":
        value = 120 - absoluteYard
    elif direction == "left":
        value = absoluteYard - 10
        
    return value

In [63]:
summary["yardsToEndZone"] = summary["playId"].apply(obtainYardsToEndZone)

In [64]:
def obtainGameClock(playId):
    idParts = playId.split(":")
    idWeek = idParts[2]
    week = weeks[int(idWeek)-1]
    
    return plays.loc[playId]["gameClock"]

In [65]:
summary["gameClock"] = summary["playId"].apply(obtainGameClock)

In [66]:
summary

,playId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath,densityDifference,heightDifference,widthDifference,cluster,homeScore,visitorScore,down,quarter,yardsToGo,yardsToEndZone,gameClock
0,2018090600:190:1,55.82550,1,1,5,0.107478,2.76,-10.15,0.0,0.0,0.0,3,1,10,39.0,13:01:00
2,2018090600:344:1,7.82150,1,1,6,0.894969,-0.36,-12.15,0.0,0.0,0.0,3,1,4,102.0,09:24:00
4,2018090600:949:1,64.43250,1,1,6,0.108641,1.64,-6.25,0.0,0.0,3.0,3,2,12,92.0,15:00:00
5,2018090600:1037:1,164.09500,2,1,4,0.036564,5.41,-9.52,1.0,0.0,3.0,3,2,7,57.0,12:53:00
8,2018090600:1801:1,126.91500,1,0,6,0.055155,2.64,-12.52,0.0,3.0,6.0,3,2,3,64.0,01:35:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4550,2018123015:2373:17,-51.20585,1,1,5,-0.117174,2.10,-11.24,0.0,14.0,13.0,3,3,2,83.0,11:58:00
4551,2018123015:2629:17,244.93410,2,2,5,0.028579,8.79,-2.86,0.0,14.0,13.0,3,3,13,58.0,07:43:00
4552,2018123015:2998:17,-72.03590,1,1,5,-0.083292,5.48,-8.06,0.0,21.0,13.0,3,3,10,80.0,04:17:00
4553,2018123015:3180:17,-55.66760,0,0,6,-0.107783,-3.37,-13.98,0.0,21.0,13.0,3,3,5,75.0,00:24:00
4554,2018123015:3969:17,303.87530,4,3,3,0.023036,7.90,-6.77,0.0,24.0,21.0,3,4,12,37.0,02:00:00

In [67]:
def evaluateDefense(playId):
    yardsToGo = plays.loc[playId]["yardsToGo"]
    offensePlayResult = plays.loc[playId]["offensePlayResult"]
    
    if offensePlayResult < yardsToGo:
        value = 1   #defensa exitosa
    else:
        value = 0   #mala defensa
        
    return value

In [68]:
plays["defenseValoration"] = plays.index.map(evaluateDefense)

In [70]:
def obtainPlayResult(playId):    
    return plays.loc[playId]["defenseValoration"]

In [71]:
summary["defenseValoration"] = summary["playId"].apply(obtainPlayResult)

In [72]:
summary

,playId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath,densityDifference,heightDifference,widthDifference,cluster,homeScore,visitorScore,down,quarter,yardsToGo,yardsToEndZone,gameClock,defenseValoration
0,2018090600:190:1,55.82550,1,1,5,0.107478,2.76,-10.15,0.0,0.0,0.0,3,1,10,39.0,13:01:00,0
2,2018090600:344:1,7.82150,1,1,6,0.894969,-0.36,-12.15,0.0,0.0,0.0,3,1,4,102.0,09:24:00,1
4,2018090600:949:1,64.43250,1,1,6,0.108641,1.64,-6.25,0.0,0.0,3.0,3,2,12,92.0,15:00:00,1
5,2018090600:1037:1,164.09500,2,1,4,0.036564,5.41,-9.52,1.0,0.0,3.0,3,2,7,57.0,12:53:00,0
8,2018090600:1801:1,126.91500,1,0,6,0.055155,2.64,-12.52,0.0,3.0,6.0,3,2,3,64.0,01:35:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4550,2018123015:2373:17,-51.20585,1,1,5,-0.117174,2.10,-11.24,0.0,14.0,13.0,3,3,2,83.0,11:58:00,1
4551,2018123015:2629:17,244.93410,2,2,5,0.028579,8.79,-2.86,0.0,14.0,13.0,3,3,13,58.0,07:43:00,1
4552,2018123015:2998:17,-72.03590,1,1,5,-0.083292,5.48,-8.06,0.0,21.0,13.0,3,3,10,80.0,04:17:00,1
4553,2018123015:3180:17,-55.66760,0,0,6,-0.107783,-3.37,-13.98,0.0,21.0,13.0,3,3,5,75.0,00:24:00,1
4554,2018123015:3969:17,303.87530,4,3,3,0.023036,7.90,-6.77,0.0,24.0,21.0,3,4,12,37.0,02:00:00,1

In [ ]:
def obtainDefenseTeam(playId):
    playIdParts = playId.split(":")
    gameId = playIdParts[0]
    visitorTeam = games.loc[int(gameId)]["visitorTeamAbbr"]
    homeTeam = games.loc[int(gameId)]["homeTeamAbbr"]
    possessionTeam = plays.loc[playId]["possessionTeam"]
    
    if possessionTeam == visitorTeam: #si equipo visitante tiene el balÃ³n, el equipo local es el que defiende
        value = homeTeam
    elif possessionTeam == homeTeam:
        value = visitorTeam
    
    return value

In [ ]:
summary["defenseTeam"] = df["playId"].apply(obtainDefenseTeam)

In [14]:
summary = summary.reindex(columns=['playId','defenseTeam', 'areaDifference', 'numberPlayersDeep',
       'numberPlayersDeepDifference', 'numberPlayersUnderneath',
       'densityDifference', 'heightDifference', 'widthDifference', 'cluster',
       'homeScore', 'visitorScore', 'down', 'quarter', 'yardsToGo',
       'yardsToEndZone', 'gameClock','defenseValoration'])

In [15]:
summary

,playId,defenseTeam,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath,densityDifference,heightDifference,widthDifference,cluster,homeScore,visitorScore,down,quarter,yardsToGo,yardsToEndZone,gameClock,defenseValoration
0,2018090600:190:1,PHI,55.82550,1,1,5,0.107478,2.76,-10.15,0.0,0.0,0.0,3,1,10,39.0,13:01:00,0
2,2018090600:344:1,ATL,7.82150,1,1,6,0.894969,-0.36,-12.15,0.0,0.0,0.0,3,1,4,102.0,09:24:00,1
4,2018090600:949:1,PHI,64.43250,1,1,6,0.108641,1.64,-6.25,0.0,0.0,3.0,3,2,12,92.0,15:00:00,1
5,2018090600:1037:1,ATL,164.09500,2,1,4,0.036564,5.41,-9.52,1.0,0.0,3.0,3,2,7,57.0,12:53:00,0
8,2018090600:1801:1,ATL,126.91500,1,0,6,0.055155,2.64,-12.52,0.0,3.0,6.0,3,2,3,64.0,01:35:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4550,2018123015:2373:17,SEA,-51.20585,1,1,5,-0.117174,2.10,-11.24,0.0,14.0,13.0,3,3,2,83.0,11:58:00,1
4551,2018123015:2629:17,SEA,244.93410,2,2,5,0.028579,8.79,-2.86,0.0,14.0,13.0,3,3,13,58.0,07:43:00,1
4552,2018123015:2998:17,SEA,-72.03590,1,1,5,-0.083292,5.48,-8.06,0.0,21.0,13.0,3,3,10,80.0,04:17:00,1
4553,2018123015:3180:17,ARI,-55.66760,0,0,6,-0.107783,-3.37,-13.98,0.0,21.0,13.0,3,3,5,75.0,00:24:00,1
4554,2018123015:3969:17,SEA,303.87530,4,3,3,0.023036,7.90,-6.77,0.0,24.0,21.0,3,4,12,37.0,02:00:00,1

In [17]:
summary.to_csv("summary_teams.csv")

In [3]:
df = pd.read_csv("summary_teams.csv",index_col=0)
df

,playId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath,densityDifference,heightDifference,widthDifference,cluster,homeScore,visitorScore,down,quarter,yardsToGo,yardsToEndZone,gameClock,defenseValoration
0,2018090600:190:1,55.82550,1,1,5,0.107478,2.76,-10.15,0.0,0.0,0.0,3,1,10,39.0,13:01:00,0
2,2018090600:344:1,7.82150,1,1,6,0.894969,-0.36,-12.15,0.0,0.0,0.0,3,1,4,102.0,09:24:00,1
4,2018090600:949:1,64.43250,1,1,6,0.108641,1.64,-6.25,0.0,0.0,3.0,3,2,12,92.0,15:00:00,1
5,2018090600:1037:1,164.09500,2,1,4,0.036564,5.41,-9.52,1.0,0.0,3.0,3,2,7,57.0,12:53:00,0
8,2018090600:1801:1,126.91500,1,0,6,0.055155,2.64,-12.52,0.0,3.0,6.0,3,2,3,64.0,01:35:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4550,2018123015:2373:17,-51.20585,1,1,5,-0.117174,2.10,-11.24,0.0,14.0,13.0,3,3,2,83.0,11:58:00,1
4551,2018123015:2629:17,244.93410,2,2,5,0.028579,8.79,-2.86,0.0,14.0,13.0,3,3,13,58.0,07:43:00,1
4552,2018123015:2998:17,-72.03590,1,1,5,-0.083292,5.48,-8.06,0.0,21.0,13.0,3,3,10,80.0,04:17:00,1
4553,2018123015:3180:17,-55.66760,0,0,6,-0.107783,-3.37,-13.98,0.0,21.0,13.0,3,3,5,75.0,00:24:00,1
4554,2018123015:3969:17,303.87530,4,3,3,0.023036,7.90,-6.77,0.0,24.0,21.0,3,4,12,37.0,02:00:00,1

In [13]:
df

,playId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath,densityDifference,heightDifference,widthDifference,cluster,homeScore,visitorScore,down,quarter,yardsToGo,yardsToEndZone,gameClock,defenseValoration,defenseTeam
0,2018090600:190:1,55.82550,1,1,5,0.107478,2.76,-10.15,0.0,0.0,0.0,3,1,10,39.0,13:01:00,0,PHI
2,2018090600:344:1,7.82150,1,1,6,0.894969,-0.36,-12.15,0.0,0.0,0.0,3,1,4,102.0,09:24:00,1,ATL
4,2018090600:949:1,64.43250,1,1,6,0.108641,1.64,-6.25,0.0,0.0,3.0,3,2,12,92.0,15:00:00,1,PHI
5,2018090600:1037:1,164.09500,2,1,4,0.036564,5.41,-9.52,1.0,0.0,3.0,3,2,7,57.0,12:53:00,0,ATL
8,2018090600:1801:1,126.91500,1,0,6,0.055155,2.64,-12.52,0.0,3.0,6.0,3,2,3,64.0,01:35:00,1,ATL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4550,2018123015:2373:17,-51.20585,1,1,5,-0.117174,2.10,-11.24,0.0,14.0,13.0,3,3,2,83.0,11:58:00,1,SEA
4551,2018123015:2629:17,244.93410,2,2,5,0.028579,8.79,-2.86,0.0,14.0,13.0,3,3,13,58.0,07:43:00,1,SEA
4552,2018123015:2998:17,-72.03590,1,1,5,-0.083292,5.48,-8.06,0.0,21.0,13.0,3,3,10,80.0,04:17:00,1,SEA
4553,2018123015:3180:17,-55.66760,0,0,6,-0.107783,-3.37,-13.98,0.0,21.0,13.0,3,3,5,75.0,00:24:00,1,ARI
4554,2018123015:3969:17,303.87530,4,3,3,0.023036,7.90,-6.77,0.0,24.0,21.0,3,4,12,37.0,02:00:00,1,SEA

Tres etiquetas:
- mala: no ha defendido bien
- buena: ha defendido bien en toda la jugada
- regular: ha defendido bien un tramo pero ha perdido la marca

In [6]:
valorations = ["regular","regular","regular","buena","mala","mala","mala","buena"] #para mi el mejor es Ja'Whaun Bentley

In [7]:
df["subjective_evaluation"] = valorations

In [8]:
df

,playerId,meanDistance,meanDistanceAfterPass,numberPlayers5yds,numberPlayers5ydsAfterPass,areaDifference,numberPlayersDeep,numberPlayersDeepDifference,numberPlayersUnderneath,densityDifference,...,widthDifference,cluster,homeScore,visitorScore,down,quarter,yardsToGo,yardsToEndZone,gameClock,subjective_evaluation
id,,,,,,,,,,,,,,,,,,,,,
2018090905:313:1,71251.0,1.949711,2.831581,1.754386,1.0,224.9914,3,3,4,0.031112,...,14.08,0.0,7.0,0.0,2,1,9,72.0,11:07:00,regular
2018090905:313:1,494287.0,13.515905,16.519959,0.000000,0.0,224.9914,3,3,4,0.031112,...,14.08,0.0,7.0,0.0,2,1,9,72.0,11:07:00,regular
2018090905:313:1,2533057.0,2.793890,2.652474,0.859649,1.0,224.9914,3,3,4,0.031112,...,14.08,0.0,7.0,0.0,2,1,9,72.0,11:07:00,regular
2018090905:313:1,2533062.0,3.299615,1.724586,1.000000,1.0,224.9914,3,3,4,0.031112,...,14.08,0.0,7.0,0.0,2,1,9,72.0,11:07:00,buena
2018090905:313:1,2541243.0,8.609330,5.575882,0.228070,0.0,224.9914,3,3,4,0.031112,...,14.08,0.0,7.0,0.0,2,1,9,72.0,11:07:00,mala
2018090905:313:1,2543699.0,13.628398,17.829817,0.333333,0.0,224.9914,3,3,4,0.031112,...,14.08,0.0,7.0,0.0,2,1,9,72.0,11:07:00,mala
2018090905:313:1,2552255.0,2.598084,2.634874,0.824561,1.0,224.9914,3,3,4,0.031112,...,14.08,0.0,7.0,0.0,2,1,9,72.0,11:07:00,mala
2018090905:313:1,2561143.0,2.976865,0.422223,0.754386,1.0,224.9914,3,3,4,0.031112,...,14.08,0.0,7.0,0.0,2,1,9,72.0,11:07:00,buena