In [1]:
import pandas as pd

Let's first analyze all the defense position we have in the raw data

In [2]:
week1 = pd.read_csv("raw_data/week1.csv")
week2 = pd.read_csv("raw_data/week2.csv")
week3 = pd.read_csv("raw_data/week3.csv")
week4 = pd.read_csv("raw_data/week4.csv")
week5 = pd.read_csv("raw_data/week5.csv")
week6 = pd.read_csv("raw_data/week6.csv")
week7 = pd.read_csv("raw_data/week7.csv")
week8 = pd.read_csv("raw_data/week8.csv")
week9 = pd.read_csv("raw_data/week9.csv")
week10 = pd.read_csv("raw_data/week10.csv")
week11 = pd.read_csv("raw_data/week11.csv")
week12 = pd.read_csv("raw_data/week12.csv")
week13 = pd.read_csv("raw_data/week13.csv")
week14 = pd.read_csv("raw_data/week14.csv")
week15 = pd.read_csv("raw_data/week15.csv")
week16 = pd.read_csv("raw_data/week16.csv")
week17 = pd.read_csv("raw_data/week17.csv")
week1

,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,gameId,playId,playDirection,route
0,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,2018090600,75,left,NaN
1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,2018090600,75,left,NaN
2,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,2018090600,75,left,HITCH
3,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,2018090600,75,left,NaN
4,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,2018090600,75,left,HITCH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986017,2018-09-11T05:29:39.900Z,33.68,43.14,1.96,3.79,0.22,281.35,309.70,None,2556277.0,Marqui Christian,41.0,SS,65,away,2018091001,4192,left,NaN
986018,2018-09-11T05:29:39.900Z,36.02,40.21,0.81,1.52,0.09,308.07,234.06,None,2556593.0,Cory Littleton,58.0,ILB,65,away,2018091001,4192,left,NaN
986019,2018-09-11T05:29:39.900Z,33.02,43.81,2.63,4.57,0.27,183.83,314.39,None,2556885.0,Jalen Richard,30.0,RB,65,home,2018091001,4192,left,SCREEN
986020,2018-09-11T05:29:39.900Z,34.13,40.86,0.15,0.72,0.02,6.17,267.87,None,2558183.0,John Johnson,43.0,SS,65,away,2018091001,4192,left,NaN
986021,2018-09-11T05:29:39.900Z,33.29,43.92,1.81,4.24,0.20,NaN,NaN,None,NaN,Football,NaN,NaN,65,football,2018091001,4192,left,NaN

In [3]:
week1.count()

time             986022
x                986022
y                986022
s                986022
a                986022
dis              986022
o                919109
dir              919109
event            986022
nflId            919109
displayName      986022
jerseyNumber     919109
position         919109
frameId          986022
team             986022
gameId           986022
playId           986022
playDirection    986022
route            273314
dtype: int64

At the moment we only want the first frameId of every play

In [4]:
week1_f1 = week1[week1["frameId"]==1]
week2_f1 = week2[week2["frameId"]==1]
week3_f1 = week3[week3["frameId"]==1]
week4_f1 = week4[week4["frameId"]==1]
week5_f1 = week5[week5["frameId"]==1]
week6_f1 = week6[week6["frameId"]==1]
week7_f1 = week7[week7["frameId"]==1]
week8_f1 = week8[week8["frameId"]==1]
week9_f1 = week9[week9["frameId"]==1]
week10_f1 = week10[week10["frameId"]==1]
week11_f1 = week11[week11["frameId"]==1]
week12_f1 = week12[week12["frameId"]==1]
week13_f1 = week13[week13["frameId"]==1]
week14_f1 = week14[week14["frameId"]==1]
week15_f1 = week15[week15["frameId"]==1]
week16_f1 = week16[week16["frameId"]==1]
week17_f1 = week17[week17["frameId"]==1]
week1_f1

,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,gameId,playId,playDirection,route
0,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,2018090600,75,left,NaN
1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,2018090600,75,left,NaN
2,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,2018090600,75,left,HITCH
3,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,2018090600,75,left,NaN
4,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,2018090600,75,left,HITCH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985057,2018-09-11T05:29:33.500Z,35.90,24.39,0.00,0.00,0.00,97.08,258.63,None,2556277.0,Marqui Christian,41.0,SS,1,away,2018091001,4192,left,NaN
985058,2018-09-11T05:29:33.500Z,36.93,36.39,0.02,0.02,0.01,95.57,111.48,None,2556593.0,Cory Littleton,58.0,ILB,1,away,2018091001,4192,left,NaN
985059,2018-09-11T05:29:33.500Z,42.53,46.29,0.00,0.00,0.00,266.37,339.77,None,2556885.0,Jalen Richard,30.0,RB,1,home,2018091001,4192,left,SCREEN
985060,2018-09-11T05:29:33.500Z,29.08,35.13,0.02,0.02,0.01,104.77,290.71,None,2558183.0,John Johnson,43.0,SS,1,away,2018091001,4192,left,NaN
985061,2018-09-11T05:29:33.500Z,41.00,29.62,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,2018091001,4192,left,NaN

In [23]:
week1_f1.to_csv("week1_frame1.csv")
week2_f1.to_csv("week2_frame1.csv")
week3_f1.to_csv("week3_frame1.csv")
week4_f1.to_csv("week4_frame1.csv")
week5_f1.to_csv("week5_frame1.csv")
week6_f1.to_csv("week6_frame1.csv")
week7_f1.to_csv("week7_frame1.csv")
week8_f1.to_csv("week8_frame1.csv")
week9_f1.to_csv("week9_frame1.csv")
week10_f1.to_csv("week10_frame1.csv")
week11_f1.to_csv("week11_frame1.csv")
week12_f1.to_csv("week12_frame1.csv")
week13_f1.to_csv("week13_frame1.csv")
week14_f1.to_csv("week14_frame1.csv")
week15_f1.to_csv("week15_frame1.csv")
week16_f1.to_csv("week16_frame1.csv")
week17_f1.to_csv("week17_frame1.csv")

In [5]:
weeks_f1 = [week1_f1,week2_f1,week3_f1,week4_f1,week5_f1,week6_f1,week7_f1,week8_f1,week9_f1,week10_f1,week11_f1,week12_f1,week13_f1,week14_f1,week15_f1,week16_f1,week17_f1]

In [6]:
positions = []
for i in weeks_f1:
    for position in i["position"].unique():
        if position not in positions:
            positions.append(position)
            
print(positions)

['QB', 'SS', 'WR', 'FS', 'RB', 'MLB', 'CB', 'TE', 'LB', 'FB', nan, 'OLB', 'HB', 'ILB', 'DL', 'DB', 'NT', 'S', 'DE', 'P', 'LS', 'K', 'DT']

In [7]:
defense_positions = ['SS','FS','MLB','CB','LB','OLB','ILB','DL','DB','NT','S','DT']

In [8]:
offense_positions = ['QB','WR','RB','TE','FB','HB']

In [9]:
special_team_positions = ['P','LS','K']

P, LS and K are frome special teams, however they act as offensive in those plays, we have to reconsider it

In [10]:
special_team_play = {}

In [11]:
cont_week = 1
for week in weeks_f1:
    for index,row in week.iterrows():
        if row["position"] in special_team_positions and row["playId"] not in special_team_play:
            special_team_play[cont_week] = row["playId"]
    cont_week += 1

In [12]:
special_team_play

{2: 329,
 3: 2100,
 4: 544,
 5: 1558,
 8: 1243,
 9: 1544,
 10: 2472,
 11: 1165,
 12: 2125,
 13: 1137,
 14: 1570,
 15: 3142,
 17: 2739}

The above plays must be removed from offensive and defensive dataframes

In [13]:
week2_f1[week2_f1["playId"]==329]

,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,gameId,playId,playDirection,route
134205,2018-09-16T17:13:17.099Z,42.38,28.55,0.11,0.06,0.01,54.13,171.81,None,2354.0,Wesley Woodyard,59.0,ILB,1,home,2018091607,329,right,NaN
134206,2018-09-16T17:13:17.099Z,30.10,29.50,0.12,0.06,0.02,80.53,143.28,None,4263.0,Brett Kern,6.0,P,1,home,2018091607,329,right,NaN
134207,2018-09-16T17:13:17.099Z,45.38,26.99,0.68,0.23,0.08,272.12,64.71,None,1037347.0,Joe Webb,5.0,QB,1,away,2018091607,329,right,NaN
134208,2018-09-16T17:13:17.099Z,42.13,31.77,0.22,0.10,0.04,90.18,212.48,None,2495234.0,Luke Stocker,88.0,TE,1,home,2018091607,329,right,NaN
134209,2018-09-16T17:13:17.099Z,44.96,24.16,0.12,0.02,0.02,281.44,230.85,None,2495251.0,Shareece Wright,43.0,CB,1,away,2018091607,329,right,NaN
134210,2018-09-16T17:13:17.099Z,44.91,34.69,0.17,0.06,0.04,274.01,233.59,None,2535693.0,Johnson Bademosi,23.0,CB,1,away,2018091607,329,right,NaN
134211,2018-09-16T17:13:17.099Z,43.39,29.91,0.18,0.03,0.02,55.04,143.36,None,2535701.0,Beau Brinkley,48.0,LS,1,home,2018091607,329,right,NaN
134212,2018-09-16T17:13:17.099Z,42.31,30.90,0.34,0.07,0.04,48.59,302.64,None,2540013.0,Will Compton,51.0,ILB,1,home,2018091607,329,right,NaN
134213,2018-09-16T17:13:17.099Z,42.61,27.72,0.13,0.05,0.02,98.46,348.47,None,2541539.0,Daren Bates,53.0,ILB,1,home,2018091607,329,right,NaN
134214,2018-09-16T17:13:17.099Z,40.30,27.10,0.34,0.51,0.03,53.43,9.78,None,2541756.0,Brynden Trawick,41.0,FS,1,home,2018091607,329,right,NaN
134215,2018-09-16T17:13:17.099Z,46.97,31.45,2.47,1.31,0.24,241.24,152.51,None,2543600.0,Alfred Blue,28.0,RB,1,away,2018091607,329,right,NaN
134216,2018-09-16T17:13:17.099Z,44.77,28.73,0.26,0.03,0.02,249.07,224.80,None,2552730.0,Brian Peters,52.0,ILB,1,away,2018091607,329,right,NaN
134217,2018-09-16T17:13:17.099Z,38.06,28.69,0.11,0.07,0.02,31.18,318.54,None,2555158.0,Kevin Byard,31.0,FS,1,home,2018091607,329,right,NaN
134218,2018-09-16T17:13:17.099Z,90.95,31.06,0.55,0.55,0.06,291.40,342.28,None,2555234.0,Tyler Ervin,21.0,RB,1,away,2018091607,329,right,NaN
134219,2018-09-16T17:13:17.099Z,42.51,44.53,0.10,0.04,0.04,53.61,334.85,None,2555551.0,LeShaun Sims,36.0,CB,1,home,2018091607,329,right,NaN
134220,2018-09-16T17:13:17.099Z,40.48,32.33,0.13,0.07,0.01,103.15,168.37,None,2558942.0,Anthony Firkser,86.0,TE,1,home,2018091607,329,right,NaN
134221,2018-09-16T17:13:17.099Z,44.45,28.40,0.08,0.23,0.00,20.06,274.16,None,2559152.0,Dylan Cole,51.0,ILB,1,away,2018091607,329,right,NaN
134222,2018-09-16T17:13:17.099Z,44.96,25.55,0.06,0.00,0.01,270.16,29.73,None,2560759.0,Natrell Jamerson,31.0,DB,1,away,2018091607,329,right,NaN
134223,2018-09-16T17:13:17.099Z,44.85,30.63,0.24,0.05,0.03,256.41,261.50,None,2560774.0,Peter Kalambayi,58.0,LB,1,away,2018091607,329,right,NaN
134224,2018-09-16T17:13:17.099Z,43.15,7.04,0.17,0.03,0.02,49.79,156.23,None,2561033.0,Dane Cruikshank,29.0,DB,1,home,2018091607,329,right,NaN
134225,2018-09-16T17:13:17.099Z,44.82,32.06,0.17,0.07,0.00,250.93,271.99,None,2561344.0,Buddy Howell,38.0,RB,1,away,2018091607,329,right,NaN
134226,2018-09-16T17:13:17.099Z,45.19,33.76,0.12,0.09,0.03,273.49,152.30,None,2561538.0,A.J. Moore,33.0,DB,1,away,2018091607,329,right,NaN
134227,2018-09-16T17:13:17.099Z,43.97,29.86,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,2018091607,329,right,NaN

The above example is a punt play. We can see we have a Punter (P) which plays for the home team, and almost 60 yards from him, a skill player (in this case a Running back (RB)) which plays for the away team. This plays are not interesting for our study, they are such a type of "outlier", they are trick plays, the defending team is not expected to play a defense play and there are different schemes.

I want to know if each play has an unique id or there are some repeated ids. I know the first play of week1 is 75, so we are going to know if it existed in other datasets.

In [14]:
play_id_test = []

In [15]:
count = 1
for week in weeks_f1:
    if (week["playId"] == 75).any():
        play_id_test.append(count)
    count+=1

In [16]:
play_id_test

[1, 2, 3, 5, 7, 8, 9, 12, 13]

The play 75 is repeated in 9 weeks, so we have to take care with this

There are also some plays which are repeated in the same dataset

In [17]:
example = week1_f1.groupby(["playId"])
example.count().max()

time             47
x                47
y                47
s                47
a                47
dis              47
o                44
dir              44
event            47
nflId            44
displayName      47
jerseyNumber     44
position         44
frameId          47
team             47
gameId           47
playDirection    47
route            15
dtype: int64

This can not be possible, in one play, the max players are 22, not 47, so this means there are some plays that are repeated

In [18]:
example_1 = week1_f1.groupby(["gameId","playId"])
example_1.count().max()

time             18
x                18
y                18
s                18
a                18
dis              18
o                17
dir              17
event            18
nflId            17
displayName      18
jerseyNumber     17
position         17
frameId          18
team             18
playDirection    18
route             5
dtype: int64

This groups have more sense, the max players playing a play is 18 (of 22)

In [19]:
first = True
for row in example_1:
    if first:
        actual_game = row[0][0]
        first = False
    elif actual_game > row[0][0]:
        print("Games are not ordered")
    else:
        actual_game = row[0][0]

Games are ordered

In [20]:
play_id_dict = {}

In [21]:
plays_by_games = []
first = True
for row in example_1:
    if first:
        plays_by_games.append(row[0][1])
        actual_game = row[0][0]
        first = False
    elif row[0][0] == actual_game:
        plays_by_games.append(row[0][1])
    else:
        play_id_dict[actual_game] = plays_by_games
        actual_game = row[0][0]
        plays_by_games = []
        plays_by_games.append(row[0][1])
        
play_id_dict[actual_game] = plays_by_games

In [22]:
play_id_dict.keys()

dict_keys([2018090600, 2018090900, 2018090901, 2018090902, 2018090903, 2018090905, 2018090906, 2018090907, 2018090909, 2018090910, 2018090912, 2018091000, 2018091001])

In [23]:
week1_f1.sort_values(['gameId','playId'])

,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,gameId,playId,playDirection,route
0,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,2018090600,75,left,NaN
1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,2018090600,75,left,NaN
2,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,2018090600,75,left,HITCH
3,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,2018090600,75,left,NaN
4,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,2018090600,75,left,HITCH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985057,2018-09-11T05:29:33.500Z,35.90,24.39,0.00,0.00,0.00,97.08,258.63,None,2556277.0,Marqui Christian,41.0,SS,1,away,2018091001,4192,left,NaN
985058,2018-09-11T05:29:33.500Z,36.93,36.39,0.02,0.02,0.01,95.57,111.48,None,2556593.0,Cory Littleton,58.0,ILB,1,away,2018091001,4192,left,NaN
985059,2018-09-11T05:29:33.500Z,42.53,46.29,0.00,0.00,0.00,266.37,339.77,None,2556885.0,Jalen Richard,30.0,RB,1,home,2018091001,4192,left,SCREEN
985060,2018-09-11T05:29:33.500Z,29.08,35.13,0.02,0.02,0.01,104.77,290.71,None,2558183.0,John Johnson,43.0,SS,1,away,2018091001,4192,left,NaN
985061,2018-09-11T05:29:33.500Z,41.00,29.62,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,2018091001,4192,left,NaN

In [24]:
for play in example_1:
    for play1 in example_1:
        if play[0][1] == play1[0][1] and play[0][0] != play1[0][0]:
            print("{} ({}) <--> {} ({})".format(play[0][1],play[0][0],play1[0][1],play1[0][0]))

402 (2018090600) <--> 402 (2018090912)
752 (2018090600) <--> 752 (2018090906)
776 (2018090600) <--> 776 (2018090906)
1085 (2018090600) <--> 1085 (2018090902)
1869 (2018090600) <--> 1869 (2018090900)
2055 (2018090600) <--> 2055 (2018090901)
2382 (2018090600) <--> 2382 (2018090902)
2575 (2018090600) <--> 2575 (2018091001)
2648 (2018090600) <--> 2648 (2018090906)
3507 (2018090600) <--> 3507 (2018090903)
3626 (2018090600) <--> 3626 (2018091001)
3904 (2018090600) <--> 3904 (2018091001)
3928 (2018090600) <--> 3928 (2018091001)
4142 (2018090600) <--> 4142 (2018090905)
210 (2018090900) <--> 210 (2018090902)
313 (2018090900) <--> 313 (2018090905)
797 (2018090900) <--> 797 (2018090902)
1316 (2018090900) <--> 1316 (2018090907)
1713 (2018090900) <--> 1713 (2018090905)
1823 (2018090900) <--> 1823 (2018090906)
1869 (2018090900) <--> 1869 (2018090600)
1906 (2018090900) <--> 1906 (2018090912)

KeyboardInterrupt:

In [25]:
week1_f1_test = week1_f1.reset_index()
week1_f1_test[week1_f1_test["playId"]==402].index

Int64Index([   98,    99,   100,   101,   102,   103,   104,   105,   106,
              107,   108,   109,   110,   111, 11735, 11736, 11737, 11738,
            11739, 11740, 11741, 11742, 11743, 11744, 11745, 11746, 11747,
            11748, 11749],
           dtype='int64')

In [26]:
week1_f1_sorted = week1_f1.sort_values(['gameId','playId'])
week1_f1_sorted.reset_index(inplace=True)

In [27]:
week1_f1_sorted[week1_f1_sorted["playId"]==402].index

Int64Index([   98,    99,   100,   101,   102,   103,   104,   105,   106,
              107,   108,   109,   110,   111, 11735, 11736, 11737, 11738,
            11739, 11740, 11741, 11742, 11743, 11744, 11745, 11746, 11747,
            11748, 11749],
           dtype='int64')

In [28]:
week1_f1_sorted[week1_f1_sorted["gameId"]==2018090912].index

Int64Index([11643, 11644, 11645, 11646, 11647, 11648, 11649, 11650, 11651,
            11652,
            ...
            12905, 12906, 12907, 12908, 12909, 12910, 12911, 12912, 12913,
            12914],
           dtype='int64', length=1272)

We know that every play is sorted

In [29]:
week1_f1_sorted.index

RangeIndex(start=0, stop=15236, step=1)

In [30]:
week1_f1_sorted = week1_f1.sort_values(['gameId','playId'])
week1_f1_sorted.reset_index(inplace=True)
week2_f1_sorted = week2_f1.sort_values(['gameId','playId'])
week2_f1_sorted.reset_index(inplace=True)
week3_f1_sorted = week3_f1.sort_values(['gameId','playId'])
week3_f1_sorted.reset_index(inplace=True)
week4_f1_sorted = week4_f1.sort_values(['gameId','playId'])
week4_f1_sorted.reset_index(inplace=True)
week5_f1_sorted = week5_f1.sort_values(['gameId','playId'])
week5_f1_sorted.reset_index(inplace=True)
week6_f1_sorted = week6_f1.sort_values(['gameId','playId'])
week6_f1_sorted.reset_index(inplace=True)
week7_f1_sorted = week7_f1.sort_values(['gameId','playId'])
week7_f1_sorted.reset_index(inplace=True)
week8_f1_sorted = week8_f1.sort_values(['gameId','playId'])
week8_f1_sorted.reset_index(inplace=True)
week9_f1_sorted = week9_f1.sort_values(['gameId','playId'])
week9_f1_sorted.reset_index(inplace=True)
week10_f1_sorted = week10_f1.sort_values(['gameId','playId'])
week10_f1_sorted.reset_index(inplace=True)
week11_f1_sorted = week11_f1.sort_values(['gameId','playId'])
week11_f1_sorted.reset_index(inplace=True)
week12_f1_sorted = week12_f1.sort_values(['gameId','playId'])
week12_f1_sorted.reset_index(inplace=True)
week13_f1_sorted = week13_f1.sort_values(['gameId','playId'])
week13_f1_sorted.reset_index(inplace=True)
week14_f1_sorted = week14_f1.sort_values(['gameId','playId'])
week14_f1_sorted.reset_index(inplace=True)
week15_f1_sorted = week15_f1.sort_values(['gameId','playId'])
week15_f1_sorted.reset_index(inplace=True)
week16_f1_sorted = week16_f1.sort_values(['gameId','playId'])
week16_f1_sorted.reset_index(inplace=True)
week17_f1_sorted = week17_f1.sort_values(['gameId','playId'])
week17_f1_sorted.reset_index(inplace=True)

In [36]:
weeks_f1_sorted = [week1_f1_sorted,week2_f1_sorted,week3_f1_sorted,week4_f1_sorted,week5_f1_sorted,week6_f1_sorted,
                   week7_f1_sorted,week8_f1_sorted,week9_f1_sorted,week10_f1_sorted,week11_f1_sorted,week12_f1_sorted,week13_f1_sorted,week14_f1_sorted,
                   week15_f1_sorted,week16_f1_sorted,week17_f1_sorted]

In [33]:
special_team_play

{2: 329,
 3: 2100,
 4: 544,
 5: 1558,
 8: 1243,
 9: 1544,
 10: 2472,
 11: 1165,
 12: 2125,
 13: 1137,
 14: 1570,
 15: 3142,
 17: 2739}

In [50]:
count = 1
for week in weeks_f1_sorted:
    if count in special_team_play.keys():
        if (week["playId"]==special_team_play[count]).value_counts()[1] > 23:
            print("Week {}: {} --> {} players and football".format(count,special_team_play[count],(week["playId"]==special_team_play[count]).value_counts()[1]))
    count+=1

Week 3: 2100 --> 27
Week 8: 1243 --> 36
Week 13: 1137 --> 35

In [40]:
(week2_f1_sorted["playId"]==329).value_counts()

False    18968
True        23
Name: playId, dtype: int64

In [44]:
(week2_f1_sorted["playId"]==329).value_counts()[0]

18968

In [51]:
week3_f1_sorted[week3_f1_sorted["playId"]==2100]

,index,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,gameId,playId,playDirection,route
7393,410061,2018-09-23T18:28:07.000Z,75.68,29.99,1.60,0.86,0.16,265.39,294.13,None,2499278.0,Malcolm Smith,51.0,OLB,1,away,2018092305,2100,right,NaN
7394,410062,2018-09-23T18:28:07.000Z,69.47,21.76,0.00,0.00,0.00,90.45,67.65,None,2540204.0,Spencer Ware,32.0,RB,1,home,2018092305,2100,right,NaN
7395,410063,2018-09-23T18:28:07.000Z,72.67,16.24,0.00,0.00,0.00,58.78,304.33,None,2541187.0,Demetrius Harris,84.0,TE,1,home,2018092305,2100,right,NaN
7396,410064,2018-09-23T18:28:07.000Z,85.41,21.66,0.00,0.00,0.00,259.57,194.02,None,2543680.0,Antone Exum,38.0,FS,1,away,2018092305,2100,right,NaN
7397,410065,2018-09-23T18:28:07.000Z,78.89,46.37,2.77,0.26,0.28,174.36,89.90,None,2543741.0,Jimmie Ward,20.0,FS,1,away,2018092305,2100,right,NaN
7398,410066,2018-09-23T18:28:07.000Z,79.66,37.65,0.02,0.02,0.01,245.61,126.68,None,2550654.0,K'Waun Williams,24.0,CB,1,away,2018092305,2100,right,NaN
7399,410067,2018-09-23T18:28:07.000Z,72.29,32.88,0.01,0.02,0.01,81.97,280.64,None,2552652.0,Chris Conley,17.0,WR,1,home,2018092305,2100,right,NaN
7400,410068,2018-09-23T18:28:07.000Z,72.29,46.33,0.00,0.00,0.00,107.30,105.08,None,2555478.0,Demarcus Robinson,11.0,WR,1,home,2018092305,2100,right,NaN
7401,410069,2018-09-23T18:28:07.000Z,72.94,37.52,0.00,0.01,0.00,88.33,352.64,None,2556214.0,Tyreek Hill,10.0,WR,1,home,2018092305,2100,right,NaN
7402,410070,2018-09-23T18:28:07.000Z,77.98,20.31,0.01,0.01,0.01,93.32,8.24,None,2557837.0,Reuben Foster,56.0,OLB,1,away,2018092305,2100,right,NaN
7403,410071,2018-09-23T18:28:07.000Z,69.47,23.91,0.10,0.08,0.01,89.30,104.81,None,2558125.0,Patrick Mahomes,15.0,QB,1,home,2018092305,2100,right,NaN
7404,410072,2018-09-23T18:28:07.000Z,76.27,15.97,0.00,0.00,0.01,276.06,96.68,None,2558157.0,Ahkello Witherspoon,23.0,CB,1,away,2018092305,2100,right,NaN
7405,410073,2018-09-23T18:28:07.000Z,89.70,30.03,0.01,0.01,0.00,266.92,75.05,None,2560850.0,D.J. Reed,32.0,DB,1,away,2018092305,2100,right,NaN
7406,410074,2018-09-23T18:28:07.000Z,79.90,29.09,0.01,0.01,0.00,265.65,275.82,None,2560917.0,Fred Warner,48.0,LB,1,away,2018092305,2100,right,NaN
7407,410075,2018-09-23T18:28:07.000Z,73.83,23.75,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,2018092305,2100,right,NaN
12021,425831,2018-09-23T18:35:52.599Z,67.89,26.35,0.03,0.05,0.03,271.70,4.95,None,2495190.0,Ryan Kerrigan,91.0,OLB,1,home,2018092309,2100,right,NaN
12022,425832,2018-09-23T18:35:52.599Z,64.98,33.60,0.00,0.00,0.00,120.10,130.11,None,2495888.0,Marcedes Lewis,89.0,TE,1,away,2018092309,2100,right,NaN
12023,425833,2018-09-23T18:35:52.599Z,56.18,31.94,0.07,0.09,0.01,120.22,355.60,None,2507232.0,Mason Crosby,2.0,K,1,away,2018092309,2100,right,NaN
12024,425834,2018-09-23T18:35:52.599Z,71.93,31.19,0.73,0.22,0.07,256.02,0.68,None,2553687.0,Zach Vigil,56.0,MLB,1,home,2018092309,2100,right,NaN
12025,425835,2018-09-23T18:35:52.599Z,68.59,25.49,0.40,1.65,0.05,324.39,264.72,None,2553710.0,Deshazor Everett,22.0,SS,1,home,2018092309,2100,right,NaN
12026,425836,2018-09-23T18:35:52.599Z,67.70,33.87,0.00,0.00,0.00,90.00,355.70,None,2557853.0,Ryan Anderson,52.0,OLB,1,home,2018092309,2100,right,NaN
12027,425837,2018-09-23T18:35:52.599Z,71.17,35.43,0.13,0.07,0.01,260.97,273.55,None,2558133.0,Montae Nicholson,35.0,FS,1,home,2018092309,2100,right,NaN
12028,425838,2018-09-23T18:35:52.599Z,119.37,29.53,0.07,0.05,0.00,266.21,7.74,None,2560764.0,Danny Johnson,41.0,DB,1,home,2018092309,2100,right,NaN
12029,425839,2018-09-23T18:35:52.599Z,59.05,29.37,0.00,0.00,0.00,338.84,150.95,None,2560868.0,JK Scott,6.0,P,1,away,2018092309,2100,right,NaN
12030,425840,2018-09-23T18:35:52.599Z,68.14,24.86,0.00,0.00,0.00,277.50,330.90,None,2560886.0,Greg Stroman,37.0,DB,1,home,2018092309,2100,right,NaN
12031,425841,2018-09-23T18:35:52.599Z,66.80,30.02,0.00,0.00,0.00,16.13,313.86,None,2561156.0,Hunter Bradley,43.0,LS,1,away,2018092309,2100,right,NaN
12032,425842,2018-09-23T18:35:52.599Z,67.11,29.94,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,2018092309,2100,right,NaN