In [1]:
import pandas as pd

In [3]:
defenses = pd.read_csv("weeks_frame1/frame1_process/defense_players_plays.csv")
defenses.head()

,Unnamed: 0,x,y,s,a,dis,o,dir,nflId,displayName,jerseyNumber,position,team,playDirection,id
0,1,88.89,36.47,0.01,0.01,0.01,105.63,66.66,79848.0,Malcolm Jenkins,27.0,SS,home,left,2018090600:75:1
1,3,86.31,22.01,0.09,0.42,0.01,70.12,168.91,2495613.0,Corey Graham,24.0,FS,home,left,2018090600:75:1
2,5,73.64,28.70,0.03,0.02,0.01,103.05,219.41,2534832.0,Rodney McLeod,23.0,FS,home,left,2018090600:75:1
3,7,86.48,31.12,0.09,0.03,0.04,95.90,33.36,2552315.0,Jordan Hicks,58.0,MLB,home,left,2018090600:75:1
4,8,82.67,20.53,0.03,0.07,0.01,81.14,174.57,2552689.0,Ronald Darby,21.0,CB,home,left,2018090600:75:1

In [4]:
plays = pd.read_csv("raw_data/plays.csv")
plays.head()

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,...,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
0,2018090600,75,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,...,0.0,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False
1,2018090600,146,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,...,0.0,13:10:00,49.0,NaN,NaN,I,0,0,-0.372360,False
2,2018090600,168,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,...,0.0,13:05:00,49.0,NaN,NaN,I,0,0,-0.702779,False
3,2018090600,190,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,...,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False
4,2018090600,256,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,...,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False

In [9]:
games = pd.read_csv("raw_data/games.csv")
games.head()

       gameId    gameDate gameTimeEastern homeTeamAbbr visitorTeamAbbr  week
0  2018090600  09/06/2018        20:20:00          PHI             ATL     1
1  2018090901  09/09/2018        13:00:00          CLE             PIT     1
2  2018090902  09/09/2018        13:00:00          IND             CIN     1
3  2018090903  09/09/2018        13:00:00          MIA             TEN     1
4  2018090900  09/09/2018        13:00:00          BAL             BUF     1

In plays, absoluteYardline is the most important column for now.

![title](resources/field.png)

First we are going to identify how many players are there in the deepzone. We are going to divide the defenses zones like the below picture.

![title](resources/zonas_defensivas.jpg)

The deep zone starts 15 yards from the line of scrimmage. It would be interesting to start with no red zones defenses, and then expand it. So let's identify no red zone defenses.

The red zone is when the attack team is inside the 20 yard of the opponent team.

In [8]:
plays_processed = plays.copy()
plays_processed.head()

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,...,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
0,2018090600,75,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,...,0.0,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False
1,2018090600,146,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,...,0.0,13:10:00,49.0,NaN,NaN,I,0,0,-0.372360,False
2,2018090600,168,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,...,0.0,13:05:00,49.0,NaN,NaN,I,0,0,-0.702779,False
3,2018090600,190,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,...,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False
4,2018090600,256,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,...,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False

In [39]:
for index,row in plays_processed.iterrows():
    week = games[games["gameId"]==row["gameId"]]["week"][0]
    playId = str(row["gameId"])+":"+str(row["playId"])+":"+str(week)
    direction_play = defenses[defenses["id"]==str(playId)]["playDirection"][0]
    print(direction_play)
    if row["absoluteYardlineNumber"] > 10 and row["absoluteYardlineNumber"] <= 30 and direction_play == "left":
        print("RZ!! on {}".format(playId))

left

KeyError: 0

In [14]:
week = games[games["gameId"]==2018090600]["week"][0]
print(week)

1

In [33]:
defenses[defenses["id"]=="2018090600:75:1"]["playDirection"][0]

'left'