In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
plays = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/plays.csv",index_col=0)

In [4]:
week1 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week1.csv")
week2 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week2.csv")
week3 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week3.csv")
week4 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week4.csv")
week5 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week5.csv")
week6 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week6.csv")
week7 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week7.csv")
week8 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week8.csv")
week9 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week9.csv")
week10 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week10.csv")
week11 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week11.csv")
week12 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week12.csv")
week13 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week13.csv")
week14 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week14.csv")
week15 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week15.csv")
week16 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week16.csv")
week17 = pd.read_csv("processed_data/remove_st_nbt_spikes_strangeplays/week17.csv")

week1.head()

,Unnamed: 0,Unnamed: 0.1,level_0,Unnamed: 0.1.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,0,0,0,0,0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,1,1,1,1,1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2,2,2,2,2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,3,3,3,3,3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,4,4,4,4,4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH

In [5]:
week1_f1 = week1[week1["frameId"]==1]
week2_f1 = week2[week2["frameId"]==1]
week3_f1 = week3[week3["frameId"]==1]
week4_f1 = week4[week4["frameId"]==1]
week5_f1 = week5[week5["frameId"]==1]
week6_f1 = week6[week6["frameId"]==1]
week7_f1 = week7[week7["frameId"]==1]
week8_f1 = week8[week8["frameId"]==1]
week9_f1 = week9[week9["frameId"]==1]
week10_f1 = week10[week10["frameId"]==1]
week11_f1 = week11[week11["frameId"]==1]
week12_f1 = week12[week12["frameId"]==1]
week13_f1 = week13[week13["frameId"]==1]
week14_f1 = week14[week14["frameId"]==1]
week15_f1 = week15[week15["frameId"]==1]
week16_f1 = week16[week16["frameId"]==1]
week17_f1 = week17[week17["frameId"]==1]
week1_f1

,Unnamed: 0,Unnamed: 0.1,level_0,Unnamed: 0.1.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,0,0,0,0,0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,1,1,1,1,1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2,2,2,2,2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,3,3,3,3,3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,4,4,4,4,4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982403,984550,984550,985057,985057,985057,2018091001:4192:1,2018-09-11T05:29:33.500Z,35.90,24.39,0.00,0.00,0.00,97.08,258.63,None,2556277.0,Marqui Christian,41.0,SS,1,away,left,NaN
982404,984551,984551,985058,985058,985058,2018091001:4192:1,2018-09-11T05:29:33.500Z,36.93,36.39,0.02,0.02,0.01,95.57,111.48,None,2556593.0,Cory Littleton,58.0,ILB,1,away,left,NaN
982405,984552,984552,985059,985059,985059,2018091001:4192:1,2018-09-11T05:29:33.500Z,42.53,46.29,0.00,0.00,0.00,266.37,339.77,None,2556885.0,Jalen Richard,30.0,RB,1,home,left,SCREEN
982406,984553,984553,985060,985060,985060,2018091001:4192:1,2018-09-11T05:29:33.500Z,29.08,35.13,0.02,0.02,0.01,104.77,290.71,None,2558183.0,John Johnson,43.0,SS,1,away,left,NaN
982407,984554,984554,985061,985061,985061,2018091001:4192:1,2018-09-11T05:29:33.500Z,41.00,29.62,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,left,NaN

In [6]:
weeks_f1 = [week1_f1,week2_f1,week3_f1,week4_f1,week5_f1,week6_f1,week7_f1,week8_f1,week9_f1,week10_f1,week11_f1,week12_f1,week13_f1,week14_f1,week15_f1,week16_f1,week17_f1]

In [7]:
all_players = pd.concat(weeks_f1)

In [8]:
len(all_players["id"].unique())

19063

In [9]:
len(plays)

19063

In [20]:
plays[plays["id"]=="2018090907:1316:1"]

,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
600,2018090907:1316:1,(5:50) (Shotgun) E.Manning pass short left to ...,2,3,16,NYG,play_type_pass,NYG,19,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,6.0,3.0,05:50:00,91.0,NaN,NaN,C,7,7,-0.904488,False

In [13]:
week8 = pd.read_csv("processed_data/clean/week1.csv",index_col=0)

In [14]:
week8[(week8["id"]=="2018090907:1316:1")&(week8["frameId"]==1)]

,Unnamed: 0.1,level_0,Unnamed: 0.1.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
567464,567464,567719,567719,567719,2018090907:1316:1,2018-09-09T17:55:40.799Z,79.92,19.52,2.42,0.25,0.24,82.69,267.57,None,494259.0,Barry Church,42.0,SS,1,away,left,NaN
567465,567465,567720,567720,567720,2018090907:1316:1,2018-09-09T17:55:40.799Z,96.08,23.59,0.11,0.08,0.02,285.26,343.86,None,2505996.0,Eli Manning,10.0,QB,1,home,left,NaN
567466,567466,567721,567721,567721,2018090907:1316:1,2018-09-09T17:55:40.799Z,93.80,28.36,0.01,0.01,0.00,211.99,65.37,None,2532835.0,Rhett Ellison,85.0,TE,1,home,left,FLAT
567467,567467,567722,567722,567722,2018090907:1316:1,2018-09-09T17:55:40.799Z,74.72,29.82,0.73,0.13,0.07,92.45,255.98,None,2532848.0,Tashaun Gipson,39.0,FS,1,away,left,NaN
567468,567468,567723,567723,567723,2018090907:1316:1,2018-09-09T17:55:40.799Z,87.66,31.29,0.00,0.00,0.02,155.19,82.16,None,2539237.0,D.J. Hayden,25.0,CB,1,away,left,NaN
567469,567469,567724,567724,567724,2018090907:1316:1,2018-09-09T17:55:40.799Z,90.50,18.09,0.00,0.00,0.00,38.10,76.39,None,2539662.0,Lerentee McCray,55.0,OLB,1,away,left,NaN
567470,567470,567725,567725,567725,2018090907:1316:1,2018-09-09T17:55:40.799Z,82.87,10.59,0.34,0.54,0.04,36.58,293.42,None,2541162.0,A.J. Bouye,21.0,CB,1,away,left,NaN
567471,567471,567726,567726,567726,2018090907:1316:1,2018-09-09T17:55:40.799Z,93.40,33.46,0.01,0.02,0.00,210.91,317.13,None,2543496.0,Odell Beckham,13.0,WR,1,home,left,CROSS
567472,567472,567727,567727,567727,2018090907:1316:1,2018-09-09T17:55:40.799Z,92.95,10.07,0.02,0.02,0.00,281.22,82.01,None,2543590.0,Cody Latimer,12.0,WR,1,home,left,POST
567473,567473,567728,567728,567728,2018090907:1316:1,2018-09-09T17:55:40.799Z,88.40,20.11,0.40,1.35,0.04,44.13,276.44,None,2543711.0,Telvin Smith,50.0,OLB,1,away,left,NaN
567474,567474,567729,567729,567729,2018090907:1316:1,2018-09-09T17:55:40.799Z,83.08,35.31,0.14,0.17,0.01,112.40,291.66,None,2555280.0,Jalen Ramsey,20.0,CB,1,away,left,NaN
567475,567475,567730,567730,567730,2018090907:1316:1,2018-09-09T17:55:40.799Z,92.22,31.07,0.00,0.01,0.01,246.25,352.85,None,2555295.0,Sterling Shepard,87.0,WR,1,home,left,CROSS
567476,567476,567731,567731,567731,2018090907:1316:1,2018-09-09T17:55:40.799Z,84.91,26.26,0.02,0.05,0.00,79.06,10.45,None,2555329.0,Myles Jack,44.0,OLB,1,away,left,NaN
567477,567477,567732,567732,567732,2018090907:1316:1,2018-09-09T17:55:40.799Z,97.06,20.96,0.01,0.01,0.00,338.51,31.58,None,2557952.0,Wayne Gallman,22.0,RB,1,home,left,NaN
567478,567478,567733,567733,567733,2018090907:1316:1,2018-09-09T17:55:40.799Z,91.43,23.63,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,left,NaN

In [9]:
games = pd.read_csv("raw_data/games.csv",index_col=0)

In [4]:
len(plays)

19239

In [10]:
len(games)

253

In [5]:
plays["quarter"].unique()

array([1, 2, 3, 4, 5])

In [11]:
plays[plays["playId"]==75]

,playId,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
gameId,,,,,,,,,,,,,,,,,,,,,,,,,,
2018090600,75,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,I_FORM,"2 RB, 1 TE, 2 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False
2018091602,75,(14:27) (Shotgun) A.Rodgers pass short right t...,1,2,8,GB,play_type_pass,GB,27,PISTOL,"1 RB, 2 TE, 2 WR",7.0,2.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,14:27:00,83.0,NaN,NaN,C,14,14,1.430144,False
2018092307,75,(14:24) (Shotgun) J.Allen pass incomplete deep...,1,2,4,BUF,play_type_pass,BUF,31,SHOTGUN,"2 RB, 1 TE, 2 WR",6.0,2.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,14:24:00,79.0,NaN,NaN,I,0,0,-0.920500,False
2018100709,75,(14:26) K.Cousins pass short right to S.Diggs ...,1,2,5,MIN,play_type_pass,MIN,30,I_FORM,"2 RB, 1 TE, 2 WR",7.0,5.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,0.0,0.0,14:26:00,80.0,NaN,NaN,C,7,7,0.969624,False
2018102108,75,(14:21) (Shotgun) C.Wentz sacked at PHI 19 for...,1,2,10,PHI,play_type_sack,PHI,25,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,3.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,14:21:00,85.0,NaN,NaN,S,-10,-10,-1.844006,False
2018102109,75,(14:30) (Shotgun) B.Mayfield pass short right ...,1,2,4,CLE,play_type_pass,CLE,31,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,14:30:00,79.0,NaN,NaN,C,5,5,0.839911,False
2018102806,75,(14:38) (No Huddle) A.Smith pass incomplete de...,1,2,6,WAS,play_type_pass,WAS,29,SINGLEBACK,"1 RB, 2 TE, 2 WR",7.0,4.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0.0,0.0,14:38:00,81.0,NaN,NaN,I,0,0,-0.923625,False
2018110100,75,"(14:40) (No Huddle, Shotgun) D.Carr pass short...",1,1,10,OAK,play_type_pass,OAK,36,EMPTY,"1 RB, 1 TE, 3 WR",5.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,14:40:00,46.0,NaN,NaN,C,2,2,-0.401067,False
2018112202,75,(14:25) (Shotgun) D.Brees pass short right to ...,1,1,10,NO,play_type_pass,NO,43,EMPTY,"1 RB, 1 TE, 3 WR",4.0,3.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,0.0,0.0,14:25:00,67.0,NaN,NaN,C,9,9,0.124570,False
2018120205,75,(14:28) C.Kessler pass short left to T.Yeldon ...,1,2,9,JAX,play_type_pass,JAX,26,SINGLEBACK,"1 RB, 1 TE, 3 WR",6.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,14:28:00,36.0,NaN,NaN,C,10,10,1.196370,False

In [6]:
plays["passResult"].unique()

array(['C', 'I', 'S', 'IN', nan, 'R'], dtype=object)

In [9]:
plays[plays["playType"]=="play_type_unknown"]["penaltyCodes"].isnull().sum()

0

In [8]:
week5["event"].unique()

array(['None', 'ball_snap', 'pass_forward', 'pass_arrived',
       'pass_outcome_caught', 'first_contact', 'tackle', 'play_action',
       'man_in_motion', 'touchdown', 'handoff', 'qb_sack',
       'pass_outcome_incomplete', 'out_of_bounds', 'line_set',
       'pass_tipped', 'pass_outcome_interception',
       'pass_outcome_touchdown', 'fumble', 'fumble_defense_recovered',
       'shift', 'qb_strip_sack', 'fumble_offense_recovered', 'lateral',
       'pass_shovel', 'run', 'penalty_accepted', 'touchback'],
      dtype=object)

In [7]:
week5 = pd.read_csv("processed_data/remove_st_nbt_spikes/week5.csv",index_col=0)
week6 = pd.read_csv("processed_data/remove_st_nbt_spikes/week6.csv",index_col=0)
week7 = pd.read_csv("processed_data/remove_st_nbt_spikes/week7.csv",index_col=0)
week11 = pd.read_csv("processed_data/remove_st_nbt_spikes/week1.csv",index_col=0)
week17 = pd.read_csv("processed_data/remove_st_nbt_spikes/week17.csv",index_col=0)

/home/villamor_coto/.local/lib/python3.9/site-packages/numpy/lib/arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [10]:
plays[plays["id"]=="2018111809:658:11"]

,level_0,index,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
11931,11984,12011,2018111809:658:11,(4:39) (Shotgun) D.Brees pass incomplete deep ...,1,1,10,NO,play_type_pass,PHI,28,SHOTGUN,"2 QB, 1 RB, 1 TE, 2 WR",8.0,4.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,0.0,3.0,04:39:00,38.0,NaN,NaN,I,0,0,-0.263717,False

In [5]:
week5[(week5["id"]== "2018100702:4007:5") & (week5["frameId"]==1)]

,level_0,Unnamed: 0.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
277588,278142,278142,279052,2018100702:4007:5,2018-10-07T20:02:30.900Z,53.88,20.75,0.00,0.00,0.00,273.76,254.23,None,2649.0,Danny Amendola,80.0,WR,1,away,left,GO
277589,278143,278143,279053,2018100702:4007:5,2018-10-07T20:02:30.900Z,39.09,46.93,0.63,0.72,0.06,117.54,292.54,None,2533060.0,Dre Kirkpatrick,27.0,CB,1,home,left,NaN
277590,278144,278144,279054,2018100702:4007:5,2018-10-07T20:02:30.900Z,29.14,34.86,0.34,0.40,0.03,114.43,222.61,None,2539233.0,Shawn Williams,36.0,SS,1,home,left,NaN
277591,278145,278145,279055,2018100702:4007:5,2018-10-07T20:02:30.900Z,53.13,17.89,0.00,0.00,0.00,284.21,282.17,None,2540202.0,Kenny Stills,10.0,WR,1,away,left,GO
277592,278146,278146,279056,2018100702:4007:5,2018-10-07T20:02:30.900Z,38.16,18.50,0.08,0.08,0.02,77.43,127.44,None,2543474.0,Darqueze Dennard,21.0,CB,1,home,left,NaN
277593,278147,278147,279057,2018100702:4007:5,2018-10-07T20:02:30.900Z,53.89,14.95,0.01,0.01,0.00,276.64,258.76,None,2550272.0,Albert Wilson,15.0,WR,1,away,left,GO
277594,278148,278148,279058,2018100702:4007:5,2018-10-07T20:02:30.900Z,57.63,32.14,0.00,0.01,0.00,275.07,61.65,None,2555230.0,Kenyan Drake,32.0,RB,1,away,left,FLAT
277595,278149,278149,279059,2018100702:4007:5,2018-10-07T20:02:30.900Z,39.83,31.84,0.00,0.00,0.00,82.13,61.40,None,2555528.0,Nick Vigil,59.0,OLB,1,home,left,NaN
277596,278150,278150,279060,2018100702:4007:5,2018-10-07T20:02:30.900Z,39.87,10.02,0.16,0.82,0.02,46.14,152.44,None,2556367.0,William Jackson,22.0,CB,1,home,left,NaN
277597,278151,278151,279061,2018100702:4007:5,2018-10-07T20:02:30.900Z,38.65,26.46,0.00,0.00,0.00,91.99,93.05,None,2558801.0,Jordan Evans,50.0,OLB,1,home,left,NaN
277598,278152,278152,279062,2018100702:4007:5,2018-10-07T20:02:30.900Z,27.11,16.36,1.00,0.30,0.10,89.00,264.90,None,2560970.0,Jessie Bates,30.0,S,1,home,left,NaN
277599,278153,278153,279063,2018100702:4007:5,2018-10-07T20:02:30.900Z,53.12,37.32,0.00,0.00,0.00,297.02,132.78,None,2560994.0,Mike Gesicki,86.0,TE,1,away,left,CORNER
277600,278154,278154,279064,2018100702:4007:5,2018-10-07T20:02:30.900Z,52.44,29.54,0.00,0.01,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,left,NaN

In [6]:
plays[plays["id"]=="2018100702:4007:5"]

,level_0,index,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
5096,5119,5128,2018100702:4007:5,(:10) (Shotgun) R.Tannehill pass incomplete sh...,4,3,10,MIA,play_type_pass,CIN,42,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,4.0,"4 DL, 2 LB, 5 DB",SCRAMBLE_ROLLOUT_RIGHT,17.0,27.0,00:10:00,52.0,NaN,NaN,I,0,0,-0.56635,False

In [14]:
week6[(week6["id"]== "2018101412:2923:6") & (week6["frameId"]==1)]

,level_0,Unnamed: 0.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
979120,980088,980088,982510,2018101412:2923:6,2018-10-15T02:39:16.000Z,80.70,34.94,4.98,1.18,0.50,55.12,21.69,None,2307.0,Orlando Scandrick,22.0,CB,1,away,left,NaN
979126,980094,980094,982516,2018101412:2923:6,2018-10-15T02:39:16.000Z,86.63,34.38,4.72,1.11,0.48,314.72,356.40,None,238498.0,Julian Edelman,11.0,WR,1,home,left,NaN
979132,980100,980100,982522,2018101412:2923:6,2018-10-15T02:39:16.000Z,85.00,32.51,0.00,0.00,0.00,266.77,255.63,None,497240.0,Rob Gronkowski,87.0,TE,1,home,left,NaN
979138,980106,980106,982528,2018101412:2923:6,2018-10-15T02:39:16.000Z,88.99,27.34,0.00,0.00,0.01,264.08,252.16,None,2504211.0,Tom Brady,12.0,QB,1,home,left,NaN
979144,980112,980112,982534,2018101412:2923:6,2018-10-15T02:39:16.000Z,85.32,16.84,0.00,0.00,0.01,277.63,278.60,None,2530515.0,Chris Hogan,15.0,WR,1,home,left,NaN
979150,980118,980118,982540,2018101412:2923:6,2018-10-15T02:39:16.000Z,69.80,28.76,0.44,0.73,0.04,105.77,171.18,None,2530794.0,Ron Parker,38.0,FS,1,away,left,NaN
979156,980124,980124,982546,2018101412:2923:6,2018-10-15T02:39:16.000Z,85.22,5.31,0.00,0.00,0.01,296.61,239.24,None,2537931.0,Josh Gordon,10.0,WR,1,home,left,NaN
979162,980130,980130,982552,2018101412:2923:6,2018-10-15T02:39:16.000Z,79.86,29.14,0.00,0.00,0.01,107.40,102.83,None,2543592.0,Anthony Hitchens,53.0,MLB,1,away,left,NaN
979168,980136,980136,982558,2018101412:2923:6,2018-10-15T02:39:16.000Z,88.78,24.91,0.00,0.00,0.01,262.20,201.81,None,2543773.0,James White,28.0,RB,1,home,left,NaN
979174,980142,980142,982564,2018101412:2923:6,2018-10-15T02:39:16.000Z,82.70,32.32,0.00,0.01,0.00,103.22,205.21,None,2552259.0,Josh Shaw,30.0,CB,1,away,left,NaN
979180,980148,980148,982570,2018101412:2923:6,2018-10-15T02:39:16.000Z,82.76,5.74,0.11,0.32,0.01,85.83,42.86,None,2552265.0,Steven Nelson,20.0,CB,1,away,left,NaN
979186,980154,980154,982576,2018101412:2923:6,2018-10-15T02:39:16.000Z,82.54,16.73,0.18,0.47,0.01,116.69,0.83,None,2555349.0,Kendall Fuller,23.0,CB,1,away,left,NaN
979192,980160,980160,982582,2018101412:2923:6,2018-10-15T02:39:16.000Z,79.85,22.85,1.24,0.91,0.13,83.58,105.51,None,2555542.0,Jordan Lucas,24.0,CB,1,away,left,NaN
979198,980166,980166,982588,2018101412:2923:6,2018-10-15T02:39:16.000Z,83.32,34.57,0.00,0.00,0.00,131.91,153.20,None,2560881.0,Breeland Speaks,57.0,LB,1,away,left,NaN
979204,980172,980172,982594,2018101412:2923:6,2018-10-15T02:39:16.000Z,89.93,27.85,0.00,0.00,0.06,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,left,NaN

In [11]:
plays[plays["id"]=="2018101412:2923:6"]

,level_0,index,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
7032,7064,7076,2018101412:2923:6,(:17) (Shotgun) T.Brady pass incomplete deep r...,3,2,9,NE,play_type_unknown,NE,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,DH;OPI,KC 23;NE 11,I,0,0,0.00036,False

In [15]:
week7[(week7["id"]== "2018102101:3078:7") & (week7["frameId"]==1)]

,level_0,Unnamed: 0.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
171099,171099,171099,172024,2018102101:3078:7,2018-10-21T22:27:59.400Z,61.62,23.74,0.0,0.0,0.00,128.01,329.76,None,4365.0,Brandon Carr,24.0,CB,1,home,left,NaN
171100,171100,171100,172025,2018102101:3078:7,2018-10-21T22:27:59.400Z,63.98,23.63,0.0,0.0,0.11,242.45,310.81,None,2495775.0,Eric Weddle,32.0,FS,1,home,left,NaN
171101,171101,171101,172026,2018102101:3078:7,2018-10-21T22:27:59.400Z,75.50,32.99,0.0,0.0,0.09,257.38,225.04,None,2504775.0,Drew Brees,9.0,QB,1,away,left,NaN
171102,171102,171102,172027,2018102101:3078:7,2018-10-21T22:27:59.400Z,69.21,35.84,0.0,0.0,0.00,79.29,184.39,None,2506122.0,Benjamin Watson,82.0,TE,1,away,left,NaN
171103,171103,171103,172028,2018102101:3078:7,2018-10-21T22:27:59.400Z,62.25,25.24,0.0,0.0,0.00,206.69,10.59,None,2540164.0,Tony Jefferson,23.0,SS,1,home,left,NaN
171104,171104,171104,172029,2018102101:3078:7,2018-10-21T22:27:59.400Z,65.79,51.08,0.0,0.0,0.00,82.39,167.33,None,2541834.0,Josh Hill,89.0,TE,1,away,left,NaN
171105,171105,171105,172030,2018102101:3078:7,2018-10-21T22:27:59.400Z,62.08,23.07,0.0,0.0,0.00,151.25,152.20,None,2543464.0,C.J. Mosley,57.0,ILB,1,home,left,NaN
171106,171106,171106,172031,2018102101:3078:7,2018-10-21T22:27:59.400Z,62.37,23.75,0.0,0.0,0.00,126.50,221.56,None,2543765.0,Brent Urban,96.0,DE,1,home,left,NaN
171107,171107,171107,172032,2018102101:3078:7,2018-10-21T22:27:59.400Z,63.14,21.38,0.0,0.0,0.00,62.70,150.98,None,2555505.0,Matt Judon,99.0,OLB,1,home,left,NaN
171108,171108,171108,172033,2018102101:3078:7,2018-10-21T22:27:59.400Z,63.11,23.63,0.0,0.0,0.03,145.89,129.11,None,2556650.0,Michael Pierce,97.0,DT,1,home,left,NaN
171109,171109,171109,172034,2018102101:3078:7,2018-10-21T22:27:59.400Z,63.29,22.19,0.0,0.0,0.02,144.14,47.92,None,2557862.0,Chris Wormley,93.0,DE,1,home,left,NaN
171113,171113,171113,172038,2018102101:3078:7,2018-10-21T22:27:59.500Z,62.53,22.58,0.0,0.0,0.00,248.84,3.45,None,2505660.0,Terrell Suggs,55.0,OLB,1,home,left,NaN
171123,171123,171123,172048,2018102101:3078:7,2018-10-21T22:27:59.599Z,73.78,49.49,0.0,0.0,0.00,70.64,167.32,None,2495466.0,Mark Ingram,22.0,RB,1,away,left,NaN
171135,171135,171135,172060,2018102101:3078:7,2018-10-21T22:27:59.599Z,68.78,46.49,0.0,0.0,0.00,58.50,143.39,None,2560878.0,Tre'Quan Smith,10.0,WR,1,away,left,NaN
171156,171156,171156,172081,2018102101:3078:7,2018-10-21T22:27:59.799Z,61.51,22.71,0.0,0.0,0.00,125.42,234.43,None,2508107.0,Jimmy Smith,22.0,CB,1,home,left,NaN
171157,171157,171157,172082,2018102101:3078:7,2018-10-21T22:27:59.799Z,72.10,49.26,0.0,0.0,0.00,274.78,182.37,None,2539303.0,Zach Line,42.0,FB,1,away,left,NaN
171166,171166,171166,172091,2018102101:3078:7,2018-10-21T22:27:59.799Z,62.13,22.33,0.0,0.0,0.00,107.29,213.66,None,2560947.0,Kenny Young,40.0,LB,1,home,left,NaN
171167,171167,171167,172092,2018102101:3078:7,2018-10-21T22:27:59.799Z,70.51,22.30,0.0,0.0,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,left,NaN

In [16]:
plays[plays["id"]=="2018102101:3078:7"]

,level_0,index,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
7309,7342,7355,2018102101:3078:7,(11:16) D.Brees sacked at NO 37 for -7 yards (...,4,1,10,NO,play_type_sack,NO,44,NaN,"2 RB, 2 TE, 1 WR",9.0,0.0,"3 DL, 4 LB, 4 DB",UNKNOWN,14.0,17.0,11:16:00,66.0,NaN,NaN,S,-7,-7,-0.892693,False

In [5]:
plays[plays["id"]=="2018101800:1846:7"]

,level_0,index,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
7154,7187,7199,2018101800:1846:7,(7:00) C.Keenum pass incomplete deep left to C...,2,1,10,DEN,play_type_pass,DEN,30,I_FORM,"2 RB, 0 TE, 3 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,28.0,3.0,07:00:00,40.0,NaN,NaN,I,0,0,-0.4728,False

In [9]:
week7[(week7["id"]=="2018101800:1846:7") & (week7["frameId"]==1)]

,level_0,Unnamed: 0.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
26598,26598,26598,26598,2018101800:1846:7,2018-10-19T01:37:20.799Z,37.89,19.74,0.00,0.00,0.00,77.78,321.38,None,497322.0,Emmanuel Sanders,10.0,WR,1,away,right,CROSS
26599,26599,26599,26599,2018101800:1846:7,2018-10-19T01:37:20.799Z,39.24,9.64,0.01,0.01,0.00,110.45,280.37,None,497328.0,Demaryius Thomas,88.0,WR,1,away,right,IN
26600,26600,26600,26600,2018101800:1846:7,2018-10-19T01:37:20.799Z,45.54,8.76,0.10,0.04,0.01,317.86,200.70,None,2495504.0,Patrick Peterson,21.0,CB,1,home,right,NaN
26601,26601,26601,26601,2018101800:1846:7,2018-10-19T01:37:20.799Z,42.03,36.25,0.68,0.78,0.07,196.96,275.04,None,2495807.0,Antoine Bethea,41.0,FS,1,home,right,NaN
26602,26602,26602,26602,2018101800:1846:7,2018-10-19T01:37:20.799Z,44.45,28.06,0.00,0.00,0.03,292.38,258.45,None,2530491.0,Josh Bynes,57.0,ILB,1,home,right,NaN
26603,26603,26603,26603,2018101800:1846:7,2018-10-19T01:37:20.799Z,38.47,29.89,0.00,0.00,0.00,85.89,45.71,None,2532888.0,Case Keenum,4.0,QB,1,away,right,NaN
26604,26604,26604,26604,2018101800:1846:7,2018-10-19T01:37:20.799Z,41.31,45.20,0.01,0.01,0.03,240.61,39.96,None,2543855.0,Bene' Benwikere,23.0,CB,1,home,right,NaN
26605,26605,26605,26605,2018101800:1846:7,2018-10-19T01:37:20.799Z,35.21,29.59,0.13,0.12,0.01,22.85,238.73,None,2555432.0,Andy Janovich,32.0,RB,1,away,right,ANGLE
26606,26606,26606,26606,2018101800:1846:7,2018-10-19T01:37:20.799Z,44.78,30.59,0.01,0.01,0.00,267.02,284.61,None,2557887.0,Haason Reddick,43.0,ILB,1,home,right,NaN
26607,26607,26607,26607,2018101800:1846:7,2018-10-19T01:37:20.799Z,42.13,21.13,0.09,0.43,0.07,330.51,323.02,None,2558009.0,Budda Baker,36.0,FS,1,home,right,NaN
26608,26608,26608,26608,2018101800:1846:7,2018-10-19T01:37:20.799Z,55.16,25.11,0.21,0.15,0.01,267.57,197.79,None,2558174.0,Rudy Ford,30.0,CB,1,home,right,NaN
26609,26609,26609,26609,2018101800:1846:7,2018-10-19T01:37:20.799Z,32.79,29.94,0.00,0.00,0.01,79.26,62.76,None,2560733.0,Royce Freeman,28.0,RB,1,away,right,OUT
26610,26610,26610,26610,2018101800:1846:7,2018-10-19T01:37:20.799Z,38.92,44.84,0.00,0.00,0.00,101.20,169.69,None,2560888.0,Courtland Sutton,14.0,WR,1,away,right,GO
26611,26611,26611,26611,2018101800:1846:7,2018-10-19T01:37:20.799Z,32.62,55.40,0.05,0.34,0.01,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,right,NaN

In [13]:
plays_raw = pd.read_csv("processed_data/new_id/plays_new_id.csv",index_col=0)

In [14]:
plays_raw[(plays_raw["absoluteYardlineNumber"].isnull())&(plays_raw["id"]=="2018101412:2923:6")]

,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
7076,2018101412:2923:6,(:17) (Shotgun) T.Brady pass incomplete deep r...,3,2,9,NE,play_type_unknown,NE,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DH;OPI,KC 23;NE 11,I,0,0,0.00036,False

In [7]:
week17[(week17["id"]=="2018123013:1515:17")& (week17["frameId"]==1)]

,level_0,Unnamed: 0.1,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
880607,880913,880913,884349,2018123013:1515:17,2018-12-30T22:23:05.200Z,71.39,38.94,0.06,0.06,0.00,95.18,313.04,None,2532861.0,Casey Hayward,26.0,CB,1,away,left,NaN
880608,880914,880914,884350,2018123013:1515:17,2018-12-30T22:23:05.200Z,77.29,28.23,0.00,0.00,0.00,253.86,285.10,None,2532888.0,Case Keenum,4.0,QB,1,home,left,NaN
880609,880915,880915,884351,2018123013:1515:17,2018-12-30T22:23:05.200Z,57.97,25.25,1.39,0.85,0.13,106.64,141.90,None,2541958.0,Jahleel Addae,37.0,SS,1,away,left,NaN
880610,880916,880916,884352,2018123013:1515:17,2018-12-30T22:23:05.200Z,61.87,33.79,0.52,1.28,0.05,95.63,79.04,None,2550842.0,Adrian Phillips,31.0,SS,1,away,left,NaN
880611,880917,880917,884353,2018123013:1515:17,2018-12-30T22:23:05.200Z,68.46,28.93,0.82,0.66,0.08,129.14,226.64,None,2552313.0,Hayes Pullard,50.0,MLB,1,away,left,NaN
880612,880918,880918,884354,2018123013:1515:17,2018-12-30T22:23:05.200Z,74.76,23.27,0.00,0.00,0.00,277.92,154.67,None,2553667.0,Matt LaCosse,83.0,TE,1,home,left,FLAT
880613,880919,880919,884355,2018123013:1515:17,2018-12-30T22:23:05.200Z,75.11,33.53,0.00,0.00,0.00,284.22,25.59,None,2555223.0,Devontae Booker,23.0,RB,1,home,left,FLAT
880614,880920,880920,884356,2018123013:1515:17,2018-12-30T22:23:05.200Z,68.79,21.30,0.30,0.35,0.03,93.14,16.33,None,2558182.0,Rayshawn Jenkins,23.0,SS,1,away,left,NaN
880615,880921,880921,884357,2018123013:1515:17,2018-12-30T22:23:05.200Z,74.38,19.65,0.00,0.00,0.01,295.68,101.17,None,2558985.0,Tim Patrick,81.0,WR,1,home,left,HITCH
880616,880922,880922,884358,2018123013:1515:17,2018-12-30T22:23:05.200Z,65.72,17.00,0.03,0.03,0.01,65.80,30.42,None,2559164.0,Michael Davis,43.0,CB,1,away,left,NaN
880617,880923,880923,884359,2018123013:1515:17,2018-12-30T22:23:05.200Z,71.12,34.56,0.69,1.69,0.06,92.53,270.27,None,2560760.0,Derwin James,33.0,S,1,away,left,NaN
880618,880924,880924,884360,2018123013:1515:17,2018-12-30T22:23:05.200Z,71.47,22.18,0.01,0.01,0.00,78.01,100.07,None,2560826.0,Uchenna Nwosu,42.0,LB,1,away,left,NaN
880619,880925,880925,884361,2018123013:1515:17,2018-12-30T22:23:05.200Z,73.52,38.76,0.02,0.01,0.02,247.86,131.97,None,2560888.0,Courtland Sutton,14.0,WR,1,home,left,HITCH
880620,880926,880926,884362,2018123013:1515:17,2018-12-30T22:23:05.200Z,72.96,21.43,0.00,0.00,0.01,285.97,292.21,None,2561002.0,DaeSean Hamilton,17.0,WR,1,home,left,HITCH
880621,880927,880927,884363,2018123013:1515:17,2018-12-30T22:23:05.200Z,72.55,28.25,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,left,NaN

In [10]:
plays[plays["id"]=="2018123013:1515:17"]

,level_0,index,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
18940,19014,19061,2018123013:1515:17,(6:47) (Shotgun) C.Keenum pass short right to ...,2,3,8,DEN,play_type_pass,DEN,37,EMPTY,"1 RB, 1 TE, 3 WR",6.0,5.0,"3 DL, 2 LB, 6 DB",TRADITIONAL,0.0,0.0,06:47:00,73.0,NaN,NaN,C,9,9,1.818608,False