In [1]:
import pandas as pd
import pickle

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
plays = pd.read_csv("processed_data/remove_st_nbt/plays.csv",index_col=0)
plays.head()

,index,id,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,typeDropback,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
0,0,2018090600:75:1,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,I_FORM,"2 RB, 1 TE, 2 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False
1,1,2018090600:146:1,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,13:10:00,49.0,NaN,NaN,I,0,0,-0.372360,False
2,2,2018090600:168:1,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,SHOTGUN,"2 RB, 1 TE, 2 WR",6.0,4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0.0,0.0,13:05:00,49.0,NaN,NaN,I,0,0,-0.702779,False
3,3,2018090600:190:1,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,5.0,"4 DL, 1 LB, 6 DB",SCRAMBLE_ROLLOUT_LEFT,0.0,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False
4,4,2018090600:256:1,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,SHOTGUN,"2 RB, 3 TE, 0 WR",8.0,6.0,"6 DL, 3 LB, 2 DB",TRADITIONAL,0.0,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False

In [4]:
week1 = pd.read_csv("processed_data/remove_st_nbt/week1.csv")
week2 = pd.read_csv("processed_data/remove_st_nbt/week2.csv")
week3 = pd.read_csv("processed_data/remove_st_nbt/week3.csv")
week4 = pd.read_csv("processed_data/remove_st_nbt/week4.csv")
week5 = pd.read_csv("processed_data/remove_st_nbt/week5.csv")
week6 = pd.read_csv("processed_data/remove_st_nbt/week6.csv")
week7 = pd.read_csv("processed_data/remove_st_nbt/week7.csv")
week8 = pd.read_csv("processed_data/remove_st_nbt/week8.csv")
week9 = pd.read_csv("processed_data/remove_st_nbt/week9.csv")
week10 = pd.read_csv("processed_data/remove_st_nbt/week10.csv")
week11 = pd.read_csv("processed_data/remove_st_nbt/week11.csv")
week12 = pd.read_csv("processed_data/remove_st_nbt/week12.csv")
week13 = pd.read_csv("processed_data/remove_st_nbt/week13.csv")
week14 = pd.read_csv("processed_data/remove_st_nbt/week14.csv")
week15 = pd.read_csv("processed_data/remove_st_nbt/week15.csv")
week16 = pd.read_csv("processed_data/remove_st_nbt/week16.csv")
week17 = pd.read_csv("processed_data/remove_st_nbt/week17.csv")
week1.head()

,Unnamed: 0,index,id,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
0,0,0,2018090600:75:1,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
1,1,1,2018090600:75:1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2,2,2,2018090600:75:1,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
3,3,3,2018090600:75:1,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
4,4,4,2018090600:75:1,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH

In [5]:
weeks = [week1,week2,week3,week4,week5,week6,week7,week8,week9,week10,week11,week12,week13,week14,week15,week16,week17]

In [6]:
pickle_file_spikes = open('resources/spikes_plays.pickle','rb')
spike_plays = pickle.load(pickle_file_spikes)
pickle_file_spikes.close()

In [7]:
spike_plays

['2018090901:5449:1',
 '2018090910:1982:1',
 '2018091300:5037:2',
 '2018091300:5083:2',
 '2018091602:3995:2',
 '2018091606:4174:2',
 '2018091607:3845:2',
 '2018091608:2207:2',
 '2018091608:4145:2',
 '2018091700:2074:2',
 '2018091700:4082:2',
 '2018091700:4152:2',
 '2018092301:2330:3',
 '2018092302:3858:3',
 '2018092303:1927:3',
 '2018092303:3857:3',
 '2018092313:1822:3',
 '2018093004:4636:4',
 '2018093004:5661:4',
 '2018093008:4177:4',
 '2018093009:4692:4',
 '2018100701:4218:5',
 '2018100702:3963:5',
 '2018100703:4173:5',
 '2018100708:1883:5',
 '2018100708:1929:5',
 '2018100709:3764:5',
 '2018100710:2268:5',
 '2018101400:4119:6',
 '2018101404:4407:6',
 '2018101405:2001:6',
 '2018101406:2175:6',
 '2018101500:3871:6',
 '2018102102:4676:7',
 '2018102803:4781:8',
 '2018102806:4107:8',
 '2018102811:3788:8',
 '2018102900:2300:8',
 '2018110403:2062:9',
 '2018110408:2158:9',
 '2018110408:4233:9',
 '2018111101:1868:10',
 '2018111102:3766:10',
 '2018111108:2188:10',
 '2018111110:4201:10',
 '2018111111:3865:10',
 '2018111200:4286:10',
 '2018111200:4336:10',
 '2018111806:4248:11',
 '2018111806:4295:11',
 '2018111807:4102:11',
 '2018111807:4232:11',
 '2018111808:4287:11',
 '2018111810:2125:11',
 '2018111810:4180:11',
 '2018112502:3974:12',
 '2018112505:2110:12',
 '2018112510:2055:12',
 '2018112600:2043:12',
 '2018120204:4359:13',
 '2018120204:4406:13',
 '2018120213:2126:13',
 '2018120213:2173:13',
 '2018121501:4370:15',
 '2018121604:2393:15',
 '2018121604:2440:15',
 '2018121605:2144:15',
 '2018121611:4686:15',
 '2018121700:4027:15',
 '2018122300:2017:16',
 '2018122304:2229:16',
 '2018122310:2233:16',
 '2018122313:4632:16',
 '2018123002:2045:17',
 '2018123014:2589:17']

In [ ]:
for play in spike_plays:
    id_parts = play.split(":")
    week = id_parts[2]
    plays.drop(plays[plays["id"]==play].index,inplace=True)
    weeks[int(week)-1].drop(weeks[int(week)-1][weeks[int(week)-1]["id"]== play].index,inplace=True)

In [ ]:
plays

In [16]:
for week in weeks:
    week.reset_index(inplace=True)

In [17]:
plays.reset_index(inplace=True)

In [ ]:
week_number = 1
for week in weeks:
    week.to_csv("processed_data/remove_st_nbt_spikes/week{}.csv".format(week_number))
    week_number+=1

In [ ]:
plays.to_csv("processed_data/remove_st_nbt_spikes/plays.csv")