In [2]:
import pandas as pd
import pickle

#Para el Ã¡rea
from shapely.geometry import Polygon
from shapely.geometry import MultiPoint 
from scipy.spatial import ConvexHull

In [3]:
pd.set_option('display.max_columns',None)

In [4]:
static_defense = pd.read_csv("../transformed_data/static_defenses_yards.csv",index_col=1)
static_defense.head()

,Unnamed: 0,defensivelinezonePlayers,deepzonePlayers,hookzonePlayers,curlzonePlayers,flatzonePlayers,defenseArea,defenseAreaCoverDefenders,width,height,numberQBs,numberWRs,numberTEs,numberRBs,numberFBs,numberOffensivePlayersAnotherPosition,numberSafeties,numberLBs,numberCBs,strongSide,numberPlayersDefenseStrongSide,numberPlayersDefenseWeakSide,numberPlayersOffenseStrongSide,numberPlayersOffenseWeakSide,differenceOffenseVsDefenseWidth,differenceOffenseVsDefenseStrongSide,differenceOffenseVsDefenseWeakSide,HeightByWeightDeep,HeightByWeightHook,HeightByWeightCurl,HeightByWeightFlat,WeightByArea,density,densityNoLine,densityInsidePoints,densityInsidePointsNoLine,playResult
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018090600:75:1,0,0,1,3,2,1,194.31095,194.31095,22.96,15.25,1,2,1,1,1,0,3,2,2,left,3,4,3,2,-0.63,0,-2,0.020227,0.018643,0.020066,0.021034,3.376032,0.036025,0.036025,6.974268,6.974268,10
2018090600:146:1,1,0,1,3,2,1,204.17725,204.17725,29.22,12.57,1,3,1,1,0,0,2,2,3,right,3,4,2,3,-1.15,-1,-1,0.020227,0.019228,0.020356,0.020455,3.178611,0.034284,0.034284,6.975511,6.975511,0
2018090600:168:1,2,0,1,2,2,2,277.65495,277.65495,33.67,15.21,1,2,1,2,0,0,2,2,3,left,5,2,4,1,0.71,-1,-1,0.020227,0.017683,0.020997,0.020745,2.337434,0.025211,0.025211,6.985594,6.985594,0
2018090600:190:1,3,1,0,2,3,1,189.16960,165.05520,26.42,12.91,1,3,1,1,0,0,3,1,3,right,2,5,2,3,-3.11,0,-2,0.000000,0.020120,0.021193,0.020455,3.192871,0.037004,0.036351,6.973569,6.969707,33
2018090600:320:1,5,1,0,3,3,1,187.12510,153.20020,27.80,13.29,1,3,1,1,0,0,2,3,3,left,3,5,3,2,-4.82,0,-3,0.000000,0.018995,0.019537,0.021279,4.281979,0.042752,0.045692,7.978624,7.980418,4

In [5]:
static_defense.drop(["Unnamed: 0"],axis=1,inplace=True)

In [6]:
plays = pd.read_csv("../processed_data/clean/plays.csv",index_col=1)
plays.head()

,Unnamed: 0,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,offenseFormation,personnelO,defendersInTheBox,numberOfPassRushers,personnelD,preSnapVisitorScore,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
id,,,,,,,,,,,,,,,,,,,,,,,,,
2018090600:75:1,0,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,I_FORM,"2 RB, 1 TE, 2 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",0.0,0.0,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False
2018090600:146:1,1,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,4.0,"4 DL, 2 LB, 5 DB",0.0,0.0,13:10:00,49.0,NaN,NaN,I,0,0,-0.372360,False
2018090600:168:1,2,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,SHOTGUN,"2 RB, 1 TE, 2 WR",6.0,4.0,"4 DL, 2 LB, 5 DB",0.0,0.0,13:05:00,49.0,NaN,NaN,I,0,0,-0.702779,False
2018090600:190:1,3,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,5.0,"4 DL, 1 LB, 6 DB",0.0,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False
2018090600:256:1,4,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,SHOTGUN,"2 RB, 3 TE, 0 WR",8.0,6.0,"6 DL, 3 LB, 2 DB",0.0,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False

In [7]:
plays.drop(["Unnamed: 0"],axis=1,inplace=True)

In [8]:
defense = pd.read_csv("../processed_data/processing_defenses/defense_players_plays_no_rz.csv",index_col=1)
defense.head()

,Unnamed: 0,x,y,s,a,dis,o,dir,nflId,displayName,jerseyNumber,position,team,playDirection
id,,,,,,,,,,,,,,
2018090600:75:1,1,88.89,36.47,0.01,0.01,0.01,105.63,66.66,79848.0,Malcolm Jenkins,27.0,SS,home,left
2018090600:75:1,3,86.31,22.01,0.09,0.42,0.01,70.12,168.91,2495613.0,Corey Graham,24.0,FS,home,left
2018090600:75:1,5,73.64,28.70,0.03,0.02,0.01,103.05,219.41,2534832.0,Rodney McLeod,23.0,FS,home,left
2018090600:75:1,7,86.48,31.12,0.09,0.03,0.04,95.90,33.36,2552315.0,Jordan Hicks,58.0,MLB,home,left
2018090600:75:1,8,82.67,20.53,0.03,0.07,0.01,81.14,174.57,2552689.0,Ronald Darby,21.0,CB,home,left

In [9]:
defense.drop(["Unnamed: 0"],axis=1,inplace=True)

In [10]:
games = pd.read_csv("../raw_data/games.csv",index_col=0)
games.head()

              gameDate gameTimeEastern homeTeamAbbr visitorTeamAbbr  week
gameId
2018090600  09/06/2018        20:20:00          PHI             ATL     1
2018090901  09/09/2018        13:00:00          CLE             PIT     1
2018090902  09/09/2018        13:00:00          IND             CIN     1
2018090903  09/09/2018        13:00:00          MIA             TEN     1
2018090900  09/09/2018        13:00:00          BAL             BUF     1

Determinar una jugada y realizar la transformaciÃ³n:
    2018090600:1037:1

In [11]:
single_summary = pd.DataFrame()

Obtener los jugadores defensivos de esa jugada:

In [12]:
defense.loc["2018090600:1037:1"]

,x,y,s,a,dis,o,dir,nflId,displayName,jerseyNumber,position,team,playDirection
id,,,,,,,,,,,,,
2018090600:1037:1,66.63,35.21,0.00,0.00,0.00,101.79,44.87,2539334.0,Desmond Trufant,21.0,CB,away,left
2018090600:1037:1,65.58,15.28,0.01,0.01,0.01,75.79,295.44,2539653.0,Robert Alford,23.0,CB,away,left
2018090600:1037:1,51.97,27.53,0.41,0.31,0.04,95.89,286.70,2543850.0,Ricardo Allen,37.0,SS,away,left
2018090600:1037:1,65.75,21.74,0.00,0.00,0.00,92.67,103.82,2555162.0,Deion Jones,45.0,MLB,away,left
2018090600:1037:1,66.90,17.19,0.00,0.01,0.00,95.69,338.77,2555255.0,De'Vondre Campbell,59.0,OLB,away,left
2018090600:1037:1,57.77,22.98,0.27,1.17,0.03,126.24,210.03,2555543.0,Keanu Neal,22.0,FS,away,left
2018090600:1037:1,65.43,28.96,0.93,0.62,0.08,96.78,190.65,2556445.0,Brian Poole,34.0,CB,away,left

In [13]:
single_summary["playerId"] = defense.loc["2018090600:1037:1"]["nflId"]
single_summary

                    playerId
id
2018090600:1037:1  2539334.0
2018090600:1037:1  2539653.0
2018090600:1037:1  2543850.0
2018090600:1037:1  2555162.0
2018090600:1037:1  2555255.0
2018090600:1037:1  2555543.0
2018090600:1037:1  2556445.0


# Individual Actions Data (p): consideramos que el jugador ejecuta una acciÃ³n en toda la jugada de la acciÃ³n, hay que sacar por tanto una acciÃ³n resumen de todas      para cada jugador p_i (i = a ... j) tenemos una serie de m caracterÃ­sticas {p_i1, p_i2, ..., p_im}

In [15]:
week1 = pd.read_csv("../processed_data/clean/week1.csv",index_col=6)
week1.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,level_0,Unnamed: 0.1.1.1,index,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
id,,,,,,,,,,,,,,,,,,,,,,,
2018090600:75:1,0,0,0,0,0,0,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,left,NaN
2018090600:75:1,1,1,1,1,1,1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,left,NaN
2018090600:75:1,2,2,2,2,2,2,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,left,HITCH
2018090600:75:1,3,3,3,3,3,3,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,left,NaN
2018090600:75:1,4,4,4,4,4,4,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,left,HITCH

In [16]:
week1.drop(["Unnamed: 0","Unnamed: 0.1","Unnamed: 0.1.1","level_0","Unnamed: 0.1.1.1","index"],axis=1,inplace=True)

In [17]:
#### Esto luego no servirÃ¡
week1_fpf = week1[week1["event"]=="pass_forward"]
week1_fpf.head()

,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
id,,,,,,,,,,,,,,,,,
2018090600:75:1,2018-09-07T01:07:18.099Z,96.43,26.78,0.84,2.05,0.08,356.40,333.39,pass_forward,310.0,Matt Ryan,2.0,QB,36,away,left,NaN
2018090600:75:1,2018-09-07T01:07:18.099Z,84.82,38.33,5.53,4.30,0.54,295.34,318.58,pass_forward,79848.0,Malcolm Jenkins,27.0,SS,36,home,left,NaN
2018090600:75:1,2018-09-07T01:07:18.099Z,80.69,44.91,3.11,6.67,0.34,155.11,297.88,pass_forward,2495454.0,Julio Jones,11.0,WR,36,away,left,HITCH
2018090600:75:1,2018-09-07T01:07:18.099Z,86.02,18.64,3.52,0.69,0.35,28.19,216.15,pass_forward,2495613.0,Corey Graham,24.0,FS,36,home,left,NaN
2018090600:75:1,2018-09-07T01:07:18.099Z,82.65,34.56,6.35,1.21,0.64,262.06,272.78,pass_forward,2533040.0,Mohamed Sanu,12.0,WR,36,away,left,HITCH

In [30]:
defense_fpf = week1_fpf[week1_fpf.index.isin(["2018090600:1037:1"]) & (week1_fpf["team"]=="away")]
defense_fpf

,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,playDirection,route
id,,,,,,,,,,,,,,,,,
2018090600:1037:1,2018-09-07T01:48:50.000Z,52.54,41.42,5.28,4.91,0.55,296.24,283.67,pass_forward,2539334.0,Desmond Trufant,21.0,CB,47,away,left,NaN
2018090600:1037:1,2018-09-07T01:48:50.000Z,54.59,16.21,0.62,6.68,0.08,359.87,294.71,pass_forward,2539653.0,Robert Alford,23.0,CB,47,away,left,NaN
2018090600:1037:1,2018-09-07T01:48:50.000Z,43.94,33.11,4.54,1.01,0.46,57.92,316.20,pass_forward,2543850.0,Ricardo Allen,37.0,SS,47,away,left,NaN
2018090600:1037:1,2018-09-07T01:48:50.000Z,74.19,23.09,3.62,3.72,0.34,117.95,152.92,pass_forward,2555162.0,Deion Jones,45.0,MLB,47,away,left,NaN
2018090600:1037:1,2018-09-07T01:48:50.000Z,54.85,24.76,5.19,4.74,0.54,240.88,274.87,pass_forward,2555255.0,De'Vondre Campbell,59.0,OLB,47,away,left,NaN
2018090600:1037:1,2018-09-07T01:48:50.000Z,44.82,21.17,3.40,3.72,0.36,95.92,260.10,pass_forward,2555543.0,Keanu Neal,22.0,FS,47,away,left,NaN
2018090600:1037:1,2018-09-07T01:48:50.000Z,64.28,38.74,6.31,1.42,0.64,76.72,350.73,pass_forward,2556445.0,Brian Poole,34.0,CB,47,away,left,NaN

# Complex Features (c): CaracterÃ­sticas dinÃ¡micas de la acciÃ³n en general. Posiblemente podrÃ­a ser cosas como variaciÃ³n de la superficie cubierta, variaciÃ³n de densidad, defensores en la zona del pase, ....

In [45]:
def obtainAreaDefense(playId):
    defenders = defense_fpf.loc[playId]
    position_players = []
    playDirection = defenders["playDirection"].values[0]
    los = plays.loc[playId]["absoluteYardlineNumber"]
    
    for index,row in defenders.iterrows():
        if row["position"] in ["DL","NT","DT","DE"]:
            continue
        
        if playDirection == "right" and row["x"] < los:
            continue
        elif playDirection == "left" and row["x"] > los:
            continue
        
        position_players.append((row["x"],row["y"]))
        
    hull = ConvexHull(position_players)
    
    return hull.volume

In [46]:
single_summary["areaDifference"] = single_summary.index.map(obtainAreaDefense) - static_defense.loc["2018090600:1037:1"]["defenseArea"]

In [51]:
def calculateNumberDeepPlayers(playId):
    los = plays.loc[playId]["absoluteYardlineNumber"]
    defenders = defense_fpf.loc[playId]
    playDirection = defenders["playDirection"].values[0]
    deepzone = -1
    
    if playDirection == "right":
        deepzone = los + 15
    elif playDirection == "left":
        deepzone = los - 15
        
    number_players=0
    for index,row in defenders.iterrows():
        if row["position"] in ["DL","NT","DT","DE"]: #muy dificil que pase, pero por si acaso
            continue
        player_x = row["x"]
        if playDirection == "right" and player_x > deepzone:
            number_players+=1
        elif playDirection == "left" and player_x < deepzone:
            number_players+=1
            
    return number_players

In [52]:
single_summary["numberPlayersDeep"] = single_summary.index.map(calculateNumberDeepPlayers)

In [63]:
single_summary["numberPlayersDeepDifference"] = single_summary["numberPlayersDeep"] - static_defense.loc["2018090600:1037:1"]["deepzonePlayers"]

In [ ]:
def calculateDensity(playId,area,deep,hook,curl,flat,dl):
    return (deep + hook + curl + flat + dl) / area

# se pueden aÃ±adir las caracterÃ­sticas estÃ¡ticas del comienzo o el cluster.

# Game context features(g): down, score ...

In [17]:
single_summary["homeScore"] = plays.loc["2018090600:1037:1"]["preSnapHomeScore"]

In [18]:
single_summary["visitorScore"] = plays.loc["2018090600:1037:1"]["preSnapVisitorScore"]

In [20]:
single_summary["down"] = plays.loc["2018090600:1037:1"]["down"]

In [36]:
single_summary["quarter"] = plays.loc["2018090600:1037:1"]["quarter"]

In [30]:
single_summary["yardsToGo"] = plays.loc["2018090600:1037:1"]["yardsToGo"]

In [31]:
def obtainYardsToEndZone(playId):
    absoluteYard = plays.loc["2018090600:1037:1"]["absoluteYardlineNumber"]
    direction = defense.loc["2018090600:1037:1"]["playDirection"][0]
    if direction == "right":
        value = 120 - absoluteYard
    elif direction == "left":
        value = absoluteYard - 10
        
    return value

In [32]:
single_summary["yardsToEndZone"] = single_summary.index.map(obtainYardsToEndZone)

In [34]:
single_summary["gameClock"] = plays.loc["2018090600:1037:1"]["gameClock"]

In [57]:
single_summary

,playerId,areaDifference,numberPlayersDeep,numberPlayersDeepDifference
id,,,,
2018090600:1037:1,2539334.0,164.095,2,1
2018090600:1037:1,2539653.0,164.095,2,1
2018090600:1037:1,2543850.0,164.095,2,1
2018090600:1037:1,2555162.0,164.095,2,1
2018090600:1037:1,2555255.0,164.095,2,1
2018090600:1037:1,2555543.0,164.095,2,1
2018090600:1037:1,2556445.0,164.095,2,1